# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.agent import Agent
from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract
from moysklad_remap_12_sdk.models.barcode import Barcode
from moysklad_remap_12_sdk.models.country import Country
from moysklad_remap_12_sdk.models.employee import Employee
from moysklad_remap_12_sdk.models.file_list import FileList
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.image_list import ImageList
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.minimum_stock_abstract import MinimumStockAbstract
from moysklad_remap_12_sdk.models.price import Price
from moysklad_remap_12_sdk.models.product import Product
from moysklad_remap_12_sdk.models.product_alcoholic import ProductAlcoholic
from moysklad_remap_12_sdk.models.product_folder import ProductFolder
from moysklad_remap_12_sdk.models.product_marker import ProductMarker
from moysklad_remap_12_sdk.models.sale_price import SalePrice
from moysklad_remap_12_sdk.models.uom import Uom
from moysklad_remap_12_sdk.models.variant_characteristic_value import VariantCharacteristicValue
from moysklad_remap_12_sdk.models.variant_pack import VariantPack
from typing import Optional, Set
from typing_extensions import Self

class AssortmentWithoutBundle(BaseModel):
    """
    Товар/услуга/модификация (без комплекта)
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID Партии")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    alcoholic: Optional[ProductAlcoholic] = None
    archived: Optional[StrictBool] = Field(default=None, description="Добавлена ли Партия в архив")
    tobacco: Optional[StrictBool] = Field(default=None, description="Признак товара, как табачной продукции")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Наименование Партии")
    code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Код Партии")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код Партии", alias="externalCode")
    path_name: Optional[StrictStr] = Field(default=None, description="Наименование группы, в которую входит услуга", alias="pathName")
    article: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Артикул")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Описание Партии")
    vat: Optional[Annotated[int, Field(le=99, strict=True, ge=0)]] = Field(default=None, description="НДС %")
    vat_enabled: Optional[StrictBool] = Field(default=None, description="Включен ли НДС для услуги", alias="vatEnabled")
    use_parent_vat: Optional[StrictBool] = Field(default=None, description="Используется ли ставка НДС родительской группы", alias="useParentVat")
    effective_vat: Optional[StrictInt] = Field(default=None, description="Реальный НДС %", alias="effectiveVat")
    effective_vat_enabled: Optional[StrictBool] = Field(default=None, description="Дополнительный признак для определения разграничения реального НДС", alias="effectiveVatEnabled")
    discount_prohibited: Optional[StrictBool] = Field(default=None, description="Признак запрета скидок", alias="discountProhibited")
    variants_count: Optional[StrictInt] = Field(default=None, description="Количество модификаций у данного товара", alias="variantsCount")
    is_serial_trackable: Optional[StrictBool] = Field(default=None, description="Учет по серийным номерам", alias="isSerialTrackable")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    group: Optional[Group] = None
    owner: Optional[Employee] = Field(default=None, description="Метаданные владельца (Сотрудника)")
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления сущности")
    weight: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Вес")
    volume: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Объем")
    buy_price: Optional[Price] = Field(default=None, description="Закупочная цена", alias="buyPrice")
    sale_prices: Optional[List[SalePrice]] = Field(default=None, description="Цены продажи", alias="salePrices")
    supplier: Optional[Agent] = Field(default=None, description="Метаданные контрагента или юрлица")
    country: Optional[Country] = Field(default=None, description="Метаданные Страны")
    uom: Optional[Uom] = Field(default=None, description="Метаданные единиц измерения")
    product_folder: Optional[ProductFolder] = Field(default=None, description="Метаданные группы Услуги", alias="productFolder")
    images: Optional[ImageList] = Field(default=None, description="Массив метаданных Изображений товара, к которому относится данная партия")
    files: Optional[FileList] = Field(default=None, description="Метаданные массива Файлов")
    barcodes: Optional[List[Barcode]] = Field(default=None, description="Штрихкоды Партии")
    packs: Optional[List[VariantPack]] = Field(default=None, description="Упаковки Модификации")
    tracking_type: Optional[StrictStr] = Field(default=None, description="Тип маркируемой продукции. Известные значения описаны в TrackingType", alias="trackingType")
    tnved: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Код ТН ВЭД")
    payment_item_type: Optional[StrictStr] = Field(default=None, description="Признак предмета расчета. Известные значения описаны в PaymentItemType", alias="paymentItemType")
    tax_system: Optional[StrictStr] = Field(default=None, description="Код системы налогообложения. Известные значения описаны в TaxSystem", alias="taxSystem")
    attributes: Optional[List[AttributeAbstract]] = Field(default=None, description="Коллекция доп. полей Партии")
    minimum_stock: Optional[MinimumStockAbstract] = Field(default=None, description="Неснижаемый остаток. Не выводится по умолчанию. Для получения передайте параметр `?fields=minimumStock`. ", alias="minimumStock")
    min_price: Optional[Price] = Field(default=None, alias="minPrice")
    weighed: Optional[StrictBool] = Field(default=None, description="Поле, показывающее является ли товар весовым")
    on_tap: Optional[StrictBool] = Field(default=None, description="Поле, показывающее является ли товар разливным", alias="onTap")
    partial_disposal: Optional[StrictBool] = Field(default=None, description="Управление состоянием частичного выбытия маркированного товара", alias="partialDisposal")
    things: Optional[List[StrictStr]] = Field(default=None, description="Серийные номера")
    sync_id: Optional[StrictStr] = Field(default=None, description="ID синхронизации", alias="syncId")
    ppe_type: Optional[StrictStr] = Field(default=None, description="Код вида номенклатурной классификации медицинских средств индивидуальной защиты. Известные значения описаны в PpeType", alias="ppeType")
    product: Optional[Product] = None
    characteristics: Optional[List[VariantCharacteristicValue]] = Field(default=None, description="Характеристики Модификации")
    assortment: Optional[ProductMarker] = Field(default=None, description="Метаданные товара/услуги/комплекта/модификации, к которой относится Партия")
    expiry_date: Optional[StrictStr] = Field(default=None, description="Срок годности Партии", alias="expiryDate")
    label: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Метка Партии")
    stock: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Остаток")
    reserve: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Резерв")
    in_transit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Ожидание", alias="inTransit")
    quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Доступно")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "alcoholic", "archived", "tobacco", "name", "code", "externalCode", "pathName", "article", "description", "vat", "vatEnabled", "useParentVat", "effectiveVat", "effectiveVatEnabled", "discountProhibited", "variantsCount", "isSerialTrackable", "shared", "group", "owner", "updated", "weight", "volume", "buyPrice", "salePrices", "supplier", "country", "uom", "productFolder", "images", "files", "barcodes", "packs", "trackingType", "tnved", "paymentItemType", "taxSystem", "attributes", "minimumStock", "minPrice", "weighed", "onTap", "partialDisposal", "things", "syncId", "ppeType", "product", "characteristics", "assortment", "expiryDate", "label", "stock", "reserve", "inTransit", "quantity"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssortmentWithoutBundle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.alcoholic:
            _dict['alcoholic'] = self.alcoholic.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        if self.buy_price:
            _dict['buyPrice'] = self.buy_price.to_dict()
        _items = []
        if self.sale_prices:
            for _item_sale_prices in self.sale_prices:
                if _item_sale_prices:
                    _items.append(_item_sale_prices.to_dict())
            _dict['salePrices'] = _items
        if self.supplier:
            _dict['supplier'] = self.supplier.to_dict()
        if self.country:
            _dict['country'] = self.country.to_dict()
        if self.uom:
            _dict['uom'] = self.uom.to_dict()
        if self.product_folder:
            _dict['productFolder'] = self.product_folder.to_dict()
        if self.images:
            _dict['images'] = self.images.to_dict()
        if self.files:
            _dict['files'] = self.files.to_dict()
        _items = []
        if self.barcodes:
            for _item_barcodes in self.barcodes:
                if _item_barcodes:
                    _items.append(_item_barcodes.to_dict())
            _dict['barcodes'] = _items
        _items = []
        if self.packs:
            for _item_packs in self.packs:
                if _item_packs:
                    _items.append(_item_packs.to_dict())
            _dict['packs'] = _items
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        if self.minimum_stock:
            _dict['minimumStock'] = self.minimum_stock.to_dict()
        if self.min_price:
            _dict['minPrice'] = self.min_price.to_dict()
        if self.product:
            _dict['product'] = self.product.to_dict()
        _items = []
        if self.characteristics:
            for _item_characteristics in self.characteristics:
                if _item_characteristics:
                    _items.append(_item_characteristics.to_dict())
            _dict['characteristics'] = _items
        if self.assortment:
            _dict['assortment'] = self.assortment.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.buy_price is None and "buy_price" in self.model_fields_set:
            _dict['buyPrice'] = None

        if self.sale_prices is None and "sale_prices" in self.model_fields_set:
            _dict['salePrices'] = None

        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        if self.uom is None and "uom" in self.model_fields_set:
            _dict['uom'] = None

        if self.product_folder is None and "product_folder" in self.model_fields_set:
            _dict['productFolder'] = None

        if self.files is None and "files" in self.model_fields_set:
            _dict['files'] = None

        if self.barcodes is None and "barcodes" in self.model_fields_set:
            _dict['barcodes'] = None

        if self.packs is None and "packs" in self.model_fields_set:
            _dict['packs'] = None

        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        if self.minimum_stock is None and "minimum_stock" in self.model_fields_set:
            _dict['minimumStock'] = None

        if self.things is None and "things" in self.model_fields_set:
            _dict['things'] = None

        if self.characteristics is None and "characteristics" in self.model_fields_set:
            _dict['characteristics'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssortmentWithoutBundle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "alcoholic": ProductAlcoholic.from_dict(obj["alcoholic"]) if obj.get("alcoholic") is not None else None,
            "archived": obj.get("archived"),
            "tobacco": obj.get("tobacco"),
            "name": obj.get("name"),
            "code": obj.get("code"),
            "externalCode": obj.get("externalCode"),
            "pathName": obj.get("pathName"),
            "article": obj.get("article"),
            "description": obj.get("description"),
            "vat": obj.get("vat"),
            "vatEnabled": obj.get("vatEnabled"),
            "useParentVat": obj.get("useParentVat"),
            "effectiveVat": obj.get("effectiveVat"),
            "effectiveVatEnabled": obj.get("effectiveVatEnabled"),
            "discountProhibited": obj.get("discountProhibited"),
            "variantsCount": obj.get("variantsCount"),
            "isSerialTrackable": obj.get("isSerialTrackable"),
            "shared": obj.get("shared"),
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "updated": obj.get("updated"),
            "weight": obj.get("weight"),
            "volume": obj.get("volume"),
            "buyPrice": Price.from_dict(obj["buyPrice"]) if obj.get("buyPrice") is not None else None,
            "salePrices": [SalePrice.from_dict(_item) for _item in obj["salePrices"]] if obj.get("salePrices") is not None else None,
            "supplier": Agent.from_dict(obj["supplier"]) if obj.get("supplier") is not None else None,
            "country": Country.from_dict(obj["country"]) if obj.get("country") is not None else None,
            "uom": Uom.from_dict(obj["uom"]) if obj.get("uom") is not None else None,
            "productFolder": ProductFolder.from_dict(obj["productFolder"]) if obj.get("productFolder") is not None else None,
            "images": ImageList.from_dict(obj["images"]) if obj.get("images") is not None else None,
            "files": FileList.from_dict(obj["files"]) if obj.get("files") is not None else None,
            "barcodes": [Barcode.from_dict(_item) for _item in obj["barcodes"]] if obj.get("barcodes") is not None else None,
            "packs": [VariantPack.from_dict(_item) for _item in obj["packs"]] if obj.get("packs") is not None else None,
            "trackingType": obj.get("trackingType"),
            "tnved": obj.get("tnved"),
            "paymentItemType": obj.get("paymentItemType"),
            "taxSystem": obj.get("taxSystem"),
            "attributes": [AttributeAbstract.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "minimumStock": MinimumStockAbstract.from_dict(obj["minimumStock"]) if obj.get("minimumStock") is not None else None,
            "minPrice": Price.from_dict(obj["minPrice"]) if obj.get("minPrice") is not None else None,
            "weighed": obj.get("weighed"),
            "onTap": obj.get("onTap"),
            "partialDisposal": obj.get("partialDisposal"),
            "things": obj.get("things"),
            "syncId": obj.get("syncId"),
            "ppeType": obj.get("ppeType"),
            "product": Product.from_dict(obj["product"]) if obj.get("product") is not None else None,
            "characteristics": [VariantCharacteristicValue.from_dict(_item) for _item in obj["characteristics"]] if obj.get("characteristics") is not None else None,
            "assortment": ProductMarker.from_dict(obj["assortment"]) if obj.get("assortment") is not None else None,
            "expiryDate": obj.get("expiryDate"),
            "label": obj.get("label"),
            "stock": obj.get("stock"),
            "reserve": obj.get("reserve"),
            "inTransit": obj.get("inTransit"),
            "quantity": obj.get("quantity")
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj



from moysklad_remap_12_sdk.models.meta import Meta







from moysklad_remap_12_sdk.models.product_alcoholic import ProductAlcoholic





































from moysklad_remap_12_sdk.models.group import Group



from moysklad_remap_12_sdk.models.employee import Employee









from moysklad_remap_12_sdk.models.price import Price




from moysklad_remap_12_sdk.models.sale_price import SalePrice


from moysklad_remap_12_sdk.models.agent import Agent



from moysklad_remap_12_sdk.models.country import Country



from moysklad_remap_12_sdk.models.uom import Uom



from moysklad_remap_12_sdk.models.product_folder import ProductFolder



from moysklad_remap_12_sdk.models.image_list import ImageList



from moysklad_remap_12_sdk.models.file_list import FileList




from moysklad_remap_12_sdk.models.barcode import Barcode



from moysklad_remap_12_sdk.models.variant_pack import VariantPack











from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract


from moysklad_remap_12_sdk.models.minimum_stock_abstract import MinimumStockAbstract



from moysklad_remap_12_sdk.models.price import Price















from moysklad_remap_12_sdk.models.product import Product




from moysklad_remap_12_sdk.models.variant_characteristic_value import VariantCharacteristicValue


from moysklad_remap_12_sdk.models.product_marker import ProductMarker















