# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.product_marker import ProductMarker
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.entity_with_meta import EntityWithMeta

class CommissionReportInReturnedPosition(EntityWithMeta):
    """
    Позиция возврата на склад комиссионера Полученного отчета комиссионера
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID позиции")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Количество товаров/услуг в позиции")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Цена товара в копейках")
    reward: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Вознаграждение")
    vat: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="НДС для позиции")
    vat_enabled: Optional[StrictBool] = Field(default=None, description="Включен ли НДС для позиции", alias="vatEnabled")
    assortment: Optional[ProductMarker] = Field(default=None, description="Метаданные товара/партии/модификации/комплекта, которую представляет позиция")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "quantity", "price", "reward", "vat", "vatEnabled", "assortment"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        parentId: str,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/commissionreportin" + "/" + parentId + "/returntocommissionerpositions" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="commissionreportinreturnedposition",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommissionReportInReturnedPosition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.assortment:
            _dict['assortment'] = self.assortment.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommissionReportInReturnedPosition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "quantity": obj.get("quantity"),
            "price": obj.get("price"),
            "reward": obj.get("reward"),
            "vat": obj.get("vat"),
            "vatEnabled": obj.get("vatEnabled"),
            "assortment": ProductMarker.from_dict(obj["assortment"]) if obj.get("assortment") is not None else None
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj



from moysklad_remap_12_sdk.models.meta import Meta

















from moysklad_remap_12_sdk.models.product_marker import ProductMarker



