# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.account import Account
from moysklad_remap_12_sdk.models.agent import Agent
from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract
from moysklad_remap_12_sdk.models.currency_rate import CurrencyRate
from moysklad_remap_12_sdk.models.employee import Employee
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.organization import Organization
from moysklad_remap_12_sdk.models.state import State
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.entity_with_meta import EntityWithMeta

class Contract(EntityWithMeta):
    """
    Договор
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID Договора")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Номер договора")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Описание Договора")
    code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Код Договора")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код Договора", alias="externalCode")
    archived: Optional[StrictBool] = Field(default=None, description="Добавлен ли Договор в архив")
    moment: Optional[StrictStr] = Field(default=None, description="Дата Договора")
    sum: Optional[StrictInt] = Field(default=None, description="Сумма Договора")
    contract_type: Optional[StrictStr] = Field(default=None, description="Тип Договора. Известные значения описаны в ContractType", alias="contractType")
    reward_type: Optional[StrictStr] = Field(default=None, description="Тип Вознаграждения. Известные значения описаны в RewardType", alias="rewardType")
    reward_percent: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="Вознаграждение в процентах (от 0 до 100)", alias="rewardPercent")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    printed: Optional[StrictBool] = Field(default=None, description="Напечатан ли документ")
    published: Optional[StrictBool] = Field(default=None, description="Опубликован ли документ")
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления сущности")
    owner: Optional[Employee] = Field(default=None, description="Метаданные владельца (Сотрудника)")
    group: Optional[Group] = None
    own_agent: Optional[Organization] = Field(default=None, alias="ownAgent")
    agent: Optional[Agent] = Field(default=None, description="Метаданные контрагента или юрлица")
    state: Optional[State] = Field(default=None, description="Метаданные статуса договора")
    organization_account: Optional[Account] = Field(default=None, description="Метаданные счета вашего юрлица", alias="organizationAccount")
    agent_account: Optional[Account] = Field(default=None, description="Метаданные счета контрагента", alias="agentAccount")
    rate: Optional[CurrencyRate] = None
    attributes: Optional[List[AttributeAbstract]] = Field(default=None, description="Коллекция доп. полей")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "name", "description", "code", "externalCode", "archived", "moment", "sum", "contractType", "rewardType", "rewardPercent", "shared", "printed", "published", "updated", "owner", "group", "ownAgent", "agent", "state", "organizationAccount", "agentAccount", "rate", "attributes"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/contract" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="contract",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Contract from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        if self.own_agent:
            _dict['ownAgent'] = self.own_agent.to_dict()
        if self.agent:
            _dict['agent'] = self.agent.to_dict()
        if self.state:
            _dict['state'] = self.state.to_dict()
        if self.organization_account:
            _dict['organizationAccount'] = self.organization_account.to_dict()
        if self.agent_account:
            _dict['agentAccount'] = self.agent_account.to_dict()
        if self.rate:
            _dict['rate'] = self.rate.to_dict()
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        if self.organization_account is None and "organization_account" in self.model_fields_set:
            _dict['organizationAccount'] = None

        if self.agent_account is None and "agent_account" in self.model_fields_set:
            _dict['agentAccount'] = None

        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Contract from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "code": obj.get("code"),
            "externalCode": obj.get("externalCode"),
            "archived": obj.get("archived"),
            "moment": obj.get("moment"),
            "sum": obj.get("sum"),
            "contractType": obj.get("contractType"),
            "rewardType": obj.get("rewardType"),
            "rewardPercent": obj.get("rewardPercent"),
            "shared": obj.get("shared"),
            "printed": obj.get("printed"),
            "published": obj.get("published"),
            "updated": obj.get("updated"),
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "ownAgent": Organization.from_dict(obj["ownAgent"]) if obj.get("ownAgent") is not None else None,
            "agent": Agent.from_dict(obj["agent"]) if obj.get("agent") is not None else None,
            "state": State.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "organizationAccount": Account.from_dict(obj["organizationAccount"]) if obj.get("organizationAccount") is not None else None,
            "agentAccount": Account.from_dict(obj["agentAccount"]) if obj.get("agentAccount") is not None else None,
            "rate": CurrencyRate.from_dict(obj["rate"]) if obj.get("rate") is not None else None,
            "attributes": [AttributeAbstract.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj



from moysklad_remap_12_sdk.models.meta import Meta



































from moysklad_remap_12_sdk.models.employee import Employee



from moysklad_remap_12_sdk.models.group import Group



from moysklad_remap_12_sdk.models.organization import Organization



from moysklad_remap_12_sdk.models.agent import Agent



from moysklad_remap_12_sdk.models.state import State



from moysklad_remap_12_sdk.models.account import Account



from moysklad_remap_12_sdk.models.account import Account



from moysklad_remap_12_sdk.models.currency_rate import CurrencyRate




from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract


