# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract
from moysklad_remap_12_sdk.models.employee_salary import EmployeeSalary
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.image import Image
from moysklad_remap_12_sdk.models.meta import Meta
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.agent import Agent

class Employee(Agent):
    """
    Сотрудник
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID сотрудника")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Наименование сотрудника")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код сотрудника", alias="externalCode")
    archived: Optional[StrictBool] = Field(default=None, description="Добавлен ли сотрудник в архив")
    created: Optional[StrictStr] = Field(default=None, description="Момент создания")
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Комментарий к сотруднику")
    email: Optional[StrictStr] = Field(default=None, description="Адрес электронной почты")
    phone: Optional[StrictStr] = Field(default=None, description="Номер телефона")
    first_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Имя", alias="firstName")
    middle_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Отчество", alias="middleName")
    last_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Фамилия", alias="lastName")
    full_name: Optional[StrictStr] = Field(default=None, description="Полное имя сотрудника", alias="fullName")
    short_fio: Optional[StrictStr] = Field(default=None, description="Краткое ФИО сотрудника", alias="shortFio")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    group: Optional[Group] = None
    owner: Optional[Employee] = Field(default=None, description="Метаданные владельца (Сотрудника)")
    inn: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="ИНН сотрудника (в формате ИНН физического лица)")
    position: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Должность сотрудника")
    uid: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Логин сотрудника")
    salary: Optional[EmployeeSalary] = None
    cashiers: Optional[List[Cashier]] = Field(default=None, description="Массив кассиров")
    image: Optional[Image] = Field(default=None, description="Фотография сотрудника")
    attributes: Optional[List[AttributeAbstract]] = Field(default=None, description="Дополнительные поля")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "name", "externalCode", "archived", "created", "updated", "description", "email", "phone", "firstName", "middleName", "lastName", "fullName", "shortFio", "shared", "group", "owner", "inn", "position", "uid", "salary", "cashiers", "image", "attributes"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/employee" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="employee",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Employee from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        if self.salary:
            _dict['salary'] = self.salary.to_dict()
        _items = []
        if self.cashiers:
            for _item_cashiers in self.cashiers:
                if _item_cashiers:
                    _items.append(_item_cashiers.to_dict())
            _dict['cashiers'] = _items
        if self.image:
            _dict['image'] = self.image.to_dict()
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.image is None and "image" in self.model_fields_set:
            _dict['image'] = None

        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Employee from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "name": obj.get("name"),
            "externalCode": obj.get("externalCode"),
            "archived": obj.get("archived"),
            "created": obj.get("created"),
            "updated": obj.get("updated"),
            "description": obj.get("description"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "firstName": obj.get("firstName"),
            "middleName": obj.get("middleName"),
            "lastName": obj.get("lastName"),
            "fullName": obj.get("fullName"),
            "shortFio": obj.get("shortFio"),
            "shared": obj.get("shared"),
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "inn": obj.get("inn"),
            "position": obj.get("position"),
            "uid": obj.get("uid"),
            "salary": EmployeeSalary.from_dict(obj["salary"]) if obj.get("salary") is not None else None,
            "cashiers": [Cashier.from_dict(_item) for _item in obj["cashiers"]] if obj.get("cashiers") is not None else None,
            "image": Image.from_dict(obj["image"]) if obj.get("image") is not None else None,
            "attributes": [AttributeAbstract.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

from moysklad_remap_12_sdk.models.cashier import Cashier
# TODO: Rewrite to not use raise_errors
Employee.model_rebuild(raise_errors=False)


from moysklad_remap_12_sdk.models.meta import Meta



































from moysklad_remap_12_sdk.models.group import Group



from moysklad_remap_12_sdk.models.employee import Employee









from moysklad_remap_12_sdk.models.employee_salary import EmployeeSalary




from moysklad_remap_12_sdk.models.cashier import Cashier


from moysklad_remap_12_sdk.models.image import Image




from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract


