# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from importlib import import_module
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from moysklad_remap_12_sdk.models.minimum_stock_all_warehouse_same import MinimumStockAllWarehouseSame
    from moysklad_remap_12_sdk.models.minimum_stock_all_warehouse_sum import MinimumStockAllWarehouseSum
    from moysklad_remap_12_sdk.models.minimum_stock_warehouse_varied import MinimumStockWarehouseVaried

class MinimumStockAbstract(BaseModel):
    """
    MinimumStockAbstract
    """ # noqa: E501
    type: StrictStr = Field(description="Тип неснижаемого остатка")
    inherited: Optional[StrictBool] = Field(default=None, description="Признак наследуемости")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["type", "inherited"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ALL_WAREHOUSE_SUM', 'ALL_WAREHOUSE_SAME', 'WAREHOUSE_VARIED']):
            raise ValueError("must be one of enum values ('ALL_WAREHOUSE_SUM', 'ALL_WAREHOUSE_SAME', 'WAREHOUSE_VARIED')")
        return value

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    __discriminator_property_name: ClassVar[str] = 'type'
    __discriminator_value_class_map: ClassVar[Dict[str, str]] = {
        'ALL_WAREHOUSE_SAME': 'MinimumStockAllWarehouseSame','ALL_WAREHOUSE_SUM': 'MinimumStockAllWarehouseSum','WAREHOUSE_VARIED': 'MinimumStockWarehouseVaried'
    }

    @classmethod
    def get_discriminator_value(cls, obj: Dict[str, Any]) -> Optional[str]:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        return None


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Union[MinimumStockAllWarehouseSame, MinimumStockAllWarehouseSum, MinimumStockWarehouseVaried]]:
        """Create an instance of MinimumStockAbstract from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.inherited is None and "inherited" in self.model_fields_set:
            _dict['inherited'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Optional[Union[MinimumStockAllWarehouseSame, MinimumStockAllWarehouseSum, MinimumStockWarehouseVaried]]:
        """Create an instance of MinimumStockAbstract from a dict"""
        object_type = cls.get_discriminator_value(obj)
        if object_type == 'MinimumStockAllWarehouseSame':
            return import_module("moysklad_remap_12_sdk.models.minimum_stock_all_warehouse_same").MinimumStockAllWarehouseSame.from_dict(obj)
        if object_type == 'MinimumStockAllWarehouseSum':
            return import_module("moysklad_remap_12_sdk.models.minimum_stock_all_warehouse_sum").MinimumStockAllWarehouseSum.from_dict(obj)
        if object_type == 'MinimumStockWarehouseVaried':
            return import_module("moysklad_remap_12_sdk.models.minimum_stock_warehouse_varied").MinimumStockWarehouseVaried.from_dict(obj)
        raise ValueError("MinimumStockAbstract failed to lookup discriminator value from " + json.dumps(obj))







