# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract
from moysklad_remap_12_sdk.models.currency_rate import CurrencyRate
from moysklad_remap_12_sdk.models.employee import Employee
from moysklad_remap_12_sdk.models.file_list import FileList
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.move_position_list import MovePositionList
from moysklad_remap_12_sdk.models.organization import Organization
from moysklad_remap_12_sdk.models.overhead import Overhead
from moysklad_remap_12_sdk.models.production_task import ProductionTask
from moysklad_remap_12_sdk.models.project import Project
from moysklad_remap_12_sdk.models.state import State
from moysklad_remap_12_sdk.models.store import Store
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.entity_with_meta import EntityWithMeta

class Move(EntityWithMeta):
    """
    Перемещение
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID Перемещения")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Наименование Перемещения")
    code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Код Перемещения")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код Перемещения", alias="externalCode")
    sync_id: Optional[StrictStr] = Field(default=None, description="ID синхронизации", alias="syncId")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Комментарий Перемещения")
    created: Optional[StrictStr] = Field(default=None, description="Дата создания")
    deleted: Optional[StrictStr] = Field(default=None, description="Момент последнего удаления Перемещения")
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления Перемещения")
    moment: Optional[StrictStr] = Field(default=None, description="Дата документа")
    applicable: Optional[StrictBool] = Field(default=None, description="Отметка о проведении")
    printed: Optional[StrictBool] = Field(default=None, description="Напечатан ли документ")
    published: Optional[StrictBool] = Field(default=None, description="Опубликован ли документ")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    sum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма Перемещения в копейках")
    organization: Optional[Organization] = None
    source_store: Optional[Store] = Field(default=None, description="Метаданные склада, с которого совершается перемещение", alias="sourceStore")
    target_store: Optional[Store] = Field(default=None, description="Метаданные склада, на который совершается перемещение", alias="targetStore")
    state: Optional[State] = Field(default=None, description="Метаданные статуса Перемещения")
    project: Optional[Project] = Field(default=None, description="Метаданные проекта")
    owner: Optional[Employee] = Field(default=None, description="Владелец (Сотрудник)")
    group: Optional[Group] = None
    attributes: Optional[List[AttributeAbstract]] = Field(default=None, description="Коллекция метаданных доп. полей")
    files: Optional[FileList] = Field(default=None, description="Метаданные массива Файлов")
    rate: Optional[CurrencyRate] = None
    positions: Optional[MovePositionList] = None
    overhead: Optional[Overhead] = None
    internal_order: Optional[InternalOrder] = Field(default=None, description="Внутренний заказ, с которым связано Перемещение", alias="internalOrder")
    customer_order: Optional[CustomerOrder] = Field(default=None, description="Заказ покупателя, с которым связано Перемещение", alias="customerOrder")
    demand: Optional[Demand] = Field(default=None, description="Отгрузка, связанная с Перемещением")
    supply: Optional[Supply] = Field(default=None, description="Приемка, связанная с Перемещением")
    production_tasks: Optional[List[ProductionTask]] = Field(default=None, description="Связанные производственные задания", alias="productionTasks")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "name", "code", "externalCode", "syncId", "description", "created", "deleted", "updated", "moment", "applicable", "printed", "published", "shared", "sum", "organization", "sourceStore", "targetStore", "state", "project", "owner", "group", "attributes", "files", "rate", "positions", "overhead", "internalOrder", "customerOrder", "demand", "supply", "productionTasks"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/move" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="move",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Move from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        if self.source_store:
            _dict['sourceStore'] = self.source_store.to_dict()
        if self.target_store:
            _dict['targetStore'] = self.target_store.to_dict()
        if self.state:
            _dict['state'] = self.state.to_dict()
        if self.project:
            _dict['project'] = self.project.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        if self.files:
            _dict['files'] = self.files.to_dict()
        if self.rate:
            _dict['rate'] = self.rate.to_dict()
        if self.positions:
            _dict['positions'] = self.positions.to_dict()
        if self.overhead:
            _dict['overhead'] = self.overhead.to_dict()
        if self.internal_order:
            _dict['internalOrder'] = self.internal_order.to_dict()
        if self.customer_order:
            _dict['customerOrder'] = self.customer_order.to_dict()
        if self.demand:
            _dict['demand'] = self.demand.to_dict()
        if self.supply:
            _dict['supply'] = self.supply.to_dict()
        _items = []
        if self.production_tasks:
            for _item_production_tasks in self.production_tasks:
                if _item_production_tasks:
                    _items.append(_item_production_tasks.to_dict())
            _dict['productionTasks'] = _items
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        if self.source_store is None and "source_store" in self.model_fields_set:
            _dict['sourceStore'] = None

        if self.target_store is None and "target_store" in self.model_fields_set:
            _dict['targetStore'] = None

        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        if self.files is None and "files" in self.model_fields_set:
            _dict['files'] = None

        if self.overhead is None and "overhead" in self.model_fields_set:
            _dict['overhead'] = None

        if self.internal_order is None and "internal_order" in self.model_fields_set:
            _dict['internalOrder'] = None

        if self.customer_order is None and "customer_order" in self.model_fields_set:
            _dict['customerOrder'] = None

        if self.production_tasks is None and "production_tasks" in self.model_fields_set:
            _dict['productionTasks'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Move from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "name": obj.get("name"),
            "code": obj.get("code"),
            "externalCode": obj.get("externalCode"),
            "syncId": obj.get("syncId"),
            "description": obj.get("description"),
            "created": obj.get("created"),
            "deleted": obj.get("deleted"),
            "updated": obj.get("updated"),
            "moment": obj.get("moment"),
            "applicable": obj.get("applicable"),
            "printed": obj.get("printed"),
            "published": obj.get("published"),
            "shared": obj.get("shared"),
            "sum": obj.get("sum"),
            "organization": Organization.from_dict(obj["organization"]) if obj.get("organization") is not None else None,
            "sourceStore": Store.from_dict(obj["sourceStore"]) if obj.get("sourceStore") is not None else None,
            "targetStore": Store.from_dict(obj["targetStore"]) if obj.get("targetStore") is not None else None,
            "state": State.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "project": Project.from_dict(obj["project"]) if obj.get("project") is not None else None,
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "attributes": [AttributeAbstract.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "files": FileList.from_dict(obj["files"]) if obj.get("files") is not None else None,
            "rate": CurrencyRate.from_dict(obj["rate"]) if obj.get("rate") is not None else None,
            "positions": MovePositionList.from_dict(obj["positions"]) if obj.get("positions") is not None else None,
            "overhead": Overhead.from_dict(obj["overhead"]) if obj.get("overhead") is not None else None,
            "internalOrder": InternalOrder.from_dict(obj["internalOrder"]) if obj.get("internalOrder") is not None else None,
            "customerOrder": CustomerOrder.from_dict(obj["customerOrder"]) if obj.get("customerOrder") is not None else None,
            "demand": Demand.from_dict(obj["demand"]) if obj.get("demand") is not None else None,
            "supply": Supply.from_dict(obj["supply"]) if obj.get("supply") is not None else None,
            "productionTasks": [ProductionTask.from_dict(_item) for _item in obj["productionTasks"]] if obj.get("productionTasks") is not None else None
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

from moysklad_remap_12_sdk.models.customer_order import CustomerOrder
from moysklad_remap_12_sdk.models.demand import Demand
from moysklad_remap_12_sdk.models.internal_order import InternalOrder
from moysklad_remap_12_sdk.models.supply import Supply
# TODO: Rewrite to not use raise_errors
Move.model_rebuild(raise_errors=False)


from moysklad_remap_12_sdk.models.meta import Meta



































from moysklad_remap_12_sdk.models.organization import Organization



from moysklad_remap_12_sdk.models.store import Store



from moysklad_remap_12_sdk.models.store import Store



from moysklad_remap_12_sdk.models.state import State



from moysklad_remap_12_sdk.models.project import Project



from moysklad_remap_12_sdk.models.employee import Employee



from moysklad_remap_12_sdk.models.group import Group




from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract


from moysklad_remap_12_sdk.models.file_list import FileList



from moysklad_remap_12_sdk.models.currency_rate import CurrencyRate



from moysklad_remap_12_sdk.models.move_position_list import MovePositionList



from moysklad_remap_12_sdk.models.overhead import Overhead



from moysklad_remap_12_sdk.models.internal_order import InternalOrder



from moysklad_remap_12_sdk.models.customer_order import CustomerOrder



from moysklad_remap_12_sdk.models.demand import Demand



from moysklad_remap_12_sdk.models.supply import Supply




from moysklad_remap_12_sdk.models.production_task import ProductionTask


