# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.account import Account
from moysklad_remap_12_sdk.models.agent import Agent
from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract
from moysklad_remap_12_sdk.models.contract import Contract
from moysklad_remap_12_sdk.models.currency_rate import CurrencyRate
from moysklad_remap_12_sdk.models.employee import Employee
from moysklad_remap_12_sdk.models.expense_item import ExpenseItem
from moysklad_remap_12_sdk.models.file_list import FileList
from moysklad_remap_12_sdk.models.finance_out_operation_abstract import FinanceOutOperationAbstract
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.organization import Organization
from moysklad_remap_12_sdk.models.project import Project
from moysklad_remap_12_sdk.models.sales_channel import SalesChannel
from moysklad_remap_12_sdk.models.state import State
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.entity_with_meta import EntityWithMeta

class PaymentOut(EntityWithMeta):
    """
    Исходящий платеж
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID Исходящего платежа")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Наименование Исходящего платежа")
    code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Код Исходящего платежа")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код Исходящего платежа", alias="externalCode")
    sync_id: Optional[StrictStr] = Field(default=None, description="ID синхронизации", alias="syncId")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Комментарий Исходящего платежа")
    created: Optional[StrictStr] = Field(default=None, description="Дата создания")
    deleted: Optional[StrictStr] = Field(default=None, description="Момент последнего удаления Исходящего платежа")
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления Исходящего платежа")
    moment: Optional[StrictStr] = Field(default=None, description="Дата документа")
    owner: Optional[Employee] = Field(default=None, description="Владелец (Сотрудник)")
    group: Optional[Group] = None
    applicable: Optional[StrictBool] = Field(default=None, description="Отметка о проведении")
    printed: Optional[StrictBool] = Field(default=None, description="Напечатан ли документ")
    published: Optional[StrictBool] = Field(default=None, description="Опубликован ли документ")
    rate: Optional[CurrencyRate] = None
    organization: Optional[Organization] = None
    agent: Optional[Agent] = Field(default=None, description="Метаданные контрагента, сотрудника или юрлица")
    expense_item: Optional[ExpenseItem] = Field(default=None, description="Метаданные статьи расходов", alias="expenseItem")
    attributes: Optional[List[AttributeAbstract]] = Field(default=None, description="Коллекция метаданных доп. полей")
    contract: Optional[Contract] = Field(default=None, description="Метаданные договора")
    files: Optional[FileList] = Field(default=None, description="Метаданные массива файлов")
    no_closing_docs: Optional[StrictBool] = Field(default=None, description="Признак \"Без закрывающих документов\"", alias="noClosingDocs")
    payment_purpose: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Назначение платежа", alias="paymentPurpose")
    project: Optional[Project] = Field(default=None, description="Метаданные проекта")
    sales_channel: Optional[SalesChannel] = Field(default=None, description="Метаданные канала продаж", alias="salesChannel")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    state: Optional[State] = Field(default=None, description="Метаданные статуса Исходящего платежа")
    sum: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Сумма Исходящего платежа в установленной валюте")
    vat_sum: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Сумма НДС", alias="vatSum")
    facture_in: Optional[FactureIn] = Field(default=None, description="Счет-фактура полученный, с которым связан этот платеж", alias="factureIn")
    agent_account: Optional[Account] = Field(default=None, description="Метаданные счета контрагента или юрлица", alias="agentAccount")
    organization_account: Optional[Account] = Field(default=None, description="Метаданные счета юрлица", alias="organizationAccount")
    operations: Optional[List[FinanceOutOperationAbstract]] = Field(default=None, description="Связанные операции: полное тело документа плюс `linkedSum`. Допустимые типы по `meta.type`: salesreturn, supply, invoicein, purchaseorder, commissionreportout ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "name", "code", "externalCode", "syncId", "description", "created", "deleted", "updated", "moment", "owner", "group", "applicable", "printed", "published", "rate", "organization", "agent", "expenseItem", "attributes", "contract", "files", "noClosingDocs", "paymentPurpose", "project", "salesChannel", "shared", "state", "sum", "vatSum", "factureIn", "agentAccount", "organizationAccount", "operations"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/paymentout" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="paymentout",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        if self.rate:
            _dict['rate'] = self.rate.to_dict()
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        if self.agent:
            _dict['agent'] = self.agent.to_dict()
        if self.expense_item:
            _dict['expenseItem'] = self.expense_item.to_dict()
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        if self.contract:
            _dict['contract'] = self.contract.to_dict()
        if self.files:
            _dict['files'] = self.files.to_dict()
        if self.project:
            _dict['project'] = self.project.to_dict()
        if self.sales_channel:
            _dict['salesChannel'] = self.sales_channel.to_dict()
        if self.state:
            _dict['state'] = self.state.to_dict()
        if self.facture_in:
            _dict['factureIn'] = self.facture_in.to_dict()
        if self.agent_account:
            _dict['agentAccount'] = self.agent_account.to_dict()
        if self.organization_account:
            _dict['organizationAccount'] = self.organization_account.to_dict()
        _items = []
        if self.operations:
            for _item_operations in self.operations:
                if _item_operations:
                    _items.append(_item_operations.to_dict())
            _dict['operations'] = _items
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.expense_item is None and "expense_item" in self.model_fields_set:
            _dict['expenseItem'] = None

        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        if self.contract is None and "contract" in self.model_fields_set:
            _dict['contract'] = None

        if self.files is None and "files" in self.model_fields_set:
            _dict['files'] = None

        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        if self.sales_channel is None and "sales_channel" in self.model_fields_set:
            _dict['salesChannel'] = None

        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        if self.facture_in is None and "facture_in" in self.model_fields_set:
            _dict['factureIn'] = None

        if self.agent_account is None and "agent_account" in self.model_fields_set:
            _dict['agentAccount'] = None

        if self.organization_account is None and "organization_account" in self.model_fields_set:
            _dict['organizationAccount'] = None

        if self.operations is None and "operations" in self.model_fields_set:
            _dict['operations'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "name": obj.get("name"),
            "code": obj.get("code"),
            "externalCode": obj.get("externalCode"),
            "syncId": obj.get("syncId"),
            "description": obj.get("description"),
            "created": obj.get("created"),
            "deleted": obj.get("deleted"),
            "updated": obj.get("updated"),
            "moment": obj.get("moment"),
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "applicable": obj.get("applicable"),
            "printed": obj.get("printed"),
            "published": obj.get("published"),
            "rate": CurrencyRate.from_dict(obj["rate"]) if obj.get("rate") is not None else None,
            "organization": Organization.from_dict(obj["organization"]) if obj.get("organization") is not None else None,
            "agent": Agent.from_dict(obj["agent"]) if obj.get("agent") is not None else None,
            "expenseItem": ExpenseItem.from_dict(obj["expenseItem"]) if obj.get("expenseItem") is not None else None,
            "attributes": [AttributeAbstract.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "contract": Contract.from_dict(obj["contract"]) if obj.get("contract") is not None else None,
            "files": FileList.from_dict(obj["files"]) if obj.get("files") is not None else None,
            "noClosingDocs": obj.get("noClosingDocs"),
            "paymentPurpose": obj.get("paymentPurpose"),
            "project": Project.from_dict(obj["project"]) if obj.get("project") is not None else None,
            "salesChannel": SalesChannel.from_dict(obj["salesChannel"]) if obj.get("salesChannel") is not None else None,
            "shared": obj.get("shared"),
            "state": State.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "sum": obj.get("sum"),
            "vatSum": obj.get("vatSum"),
            "factureIn": FactureIn.from_dict(obj["factureIn"]) if obj.get("factureIn") is not None else None,
            "agentAccount": Account.from_dict(obj["agentAccount"]) if obj.get("agentAccount") is not None else None,
            "organizationAccount": Account.from_dict(obj["organizationAccount"]) if obj.get("organizationAccount") is not None else None,
            "operations": [FinanceOutOperationAbstract.from_dict(_item) for _item in obj["operations"]] if obj.get("operations") is not None else None
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

from moysklad_remap_12_sdk.models.facture_in import FactureIn
# TODO: Rewrite to not use raise_errors
PaymentOut.model_rebuild(raise_errors=False)


from moysklad_remap_12_sdk.models.meta import Meta

























from moysklad_remap_12_sdk.models.employee import Employee



from moysklad_remap_12_sdk.models.group import Group









from moysklad_remap_12_sdk.models.currency_rate import CurrencyRate



from moysklad_remap_12_sdk.models.organization import Organization



from moysklad_remap_12_sdk.models.agent import Agent



from moysklad_remap_12_sdk.models.expense_item import ExpenseItem




from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract


from moysklad_remap_12_sdk.models.contract import Contract



from moysklad_remap_12_sdk.models.file_list import FileList







from moysklad_remap_12_sdk.models.project import Project



from moysklad_remap_12_sdk.models.sales_channel import SalesChannel





from moysklad_remap_12_sdk.models.state import State







from moysklad_remap_12_sdk.models.facture_in import FactureIn



from moysklad_remap_12_sdk.models.account import Account



from moysklad_remap_12_sdk.models.account import Account




from moysklad_remap_12_sdk.models.finance_out_operation_abstract import FinanceOutOperationAbstract


