# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.account import Account
from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract
from moysklad_remap_12_sdk.models.employee import Employee
from moysklad_remap_12_sdk.models.file_list import FileList
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.organization import Organization
from moysklad_remap_12_sdk.models.processing_material_list import ProcessingMaterialList
from moysklad_remap_12_sdk.models.processing_plan import ProcessingPlan
from moysklad_remap_12_sdk.models.processing_product_list import ProcessingProductList
from moysklad_remap_12_sdk.models.project import Project
from moysklad_remap_12_sdk.models.state import State
from moysklad_remap_12_sdk.models.store import Store
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.entity_with_meta import EntityWithMeta

class Processing(EntityWithMeta):
    """
    Техоперация
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID техоперации")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Наименование техоперации")
    code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Код техоперации")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код техоперации", alias="externalCode")
    sync_id: Optional[StrictStr] = Field(default=None, description="ID синхронизации", alias="syncId")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Комментарий техоперации")
    created: Optional[StrictStr] = Field(default=None, description="Дата создания")
    deleted: Optional[StrictStr] = Field(default=None, description="Момент последнего удаления техоперации")
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления техоперации")
    moment: Optional[StrictStr] = Field(default=None, description="Дата документа")
    applicable: Optional[StrictBool] = Field(default=None, description="Отметка о проведении")
    printed: Optional[StrictBool] = Field(default=None, description="Напечатан ли документ")
    published: Optional[StrictBool] = Field(default=None, description="Опубликован ли документ")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    organization: Optional[Organization] = None
    organization_account: Optional[Account] = Field(default=None, description="Метаданные счета юрлица", alias="organizationAccount")
    processing_plan: Optional[ProcessingPlan] = Field(default=None, description="Метаданные техкарты", alias="processingPlan")
    processing_order: Optional[ProcessingOrder] = Field(default=None, description="Метаданные заказа на производство", alias="processingOrder")
    project: Optional[Project] = Field(default=None, description="Метаданные проекта")
    owner: Optional[Employee] = Field(default=None, description="Владелец (Сотрудник)")
    group: Optional[Group] = None
    state: Optional[State] = Field(default=None, description="Метаданные статуса техоперации")
    attributes: Optional[List[AttributeAbstract]] = Field(default=None, description="Коллекция метаданных доп. полей")
    files: Optional[FileList] = Field(default=None, description="Метаданные массива файлов")
    products_store: Optional[Store] = Field(default=None, alias="productsStore")
    materials_store: Optional[Store] = Field(default=None, alias="materialsStore")
    products: Optional[ProcessingProductList] = None
    materials: Optional[ProcessingMaterialList] = None
    quantity: Optional[Union[Annotated[float, Field(strict=True, ge=0.00010)], Annotated[int, Field(strict=True, ge=1)]]] = Field(default=None, description="Объем производства")
    processing_sum: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Затраты на производство за единицу объема производства", alias="processingSum")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "name", "code", "externalCode", "syncId", "description", "created", "deleted", "updated", "moment", "applicable", "printed", "published", "shared", "organization", "organizationAccount", "processingPlan", "processingOrder", "project", "owner", "group", "state", "attributes", "files", "productsStore", "materialsStore", "products", "materials", "quantity", "processingSum"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/processing" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="processing",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Processing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        if self.organization_account:
            _dict['organizationAccount'] = self.organization_account.to_dict()
        if self.processing_plan:
            _dict['processingPlan'] = self.processing_plan.to_dict()
        if self.processing_order:
            _dict['processingOrder'] = self.processing_order.to_dict()
        if self.project:
            _dict['project'] = self.project.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        if self.state:
            _dict['state'] = self.state.to_dict()
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        if self.files:
            _dict['files'] = self.files.to_dict()
        if self.products_store:
            _dict['productsStore'] = self.products_store.to_dict()
        if self.materials_store:
            _dict['materialsStore'] = self.materials_store.to_dict()
        if self.products:
            _dict['products'] = self.products.to_dict()
        if self.materials:
            _dict['materials'] = self.materials.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        if self.organization_account is None and "organization_account" in self.model_fields_set:
            _dict['organizationAccount'] = None

        if self.processing_plan is None and "processing_plan" in self.model_fields_set:
            _dict['processingPlan'] = None

        if self.processing_order is None and "processing_order" in self.model_fields_set:
            _dict['processingOrder'] = None

        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        if self.files is None and "files" in self.model_fields_set:
            _dict['files'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Processing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "name": obj.get("name"),
            "code": obj.get("code"),
            "externalCode": obj.get("externalCode"),
            "syncId": obj.get("syncId"),
            "description": obj.get("description"),
            "created": obj.get("created"),
            "deleted": obj.get("deleted"),
            "updated": obj.get("updated"),
            "moment": obj.get("moment"),
            "applicable": obj.get("applicable"),
            "printed": obj.get("printed"),
            "published": obj.get("published"),
            "shared": obj.get("shared"),
            "organization": Organization.from_dict(obj["organization"]) if obj.get("organization") is not None else None,
            "organizationAccount": Account.from_dict(obj["organizationAccount"]) if obj.get("organizationAccount") is not None else None,
            "processingPlan": ProcessingPlan.from_dict(obj["processingPlan"]) if obj.get("processingPlan") is not None else None,
            "processingOrder": ProcessingOrder.from_dict(obj["processingOrder"]) if obj.get("processingOrder") is not None else None,
            "project": Project.from_dict(obj["project"]) if obj.get("project") is not None else None,
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "state": State.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "attributes": [AttributeAbstract.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "files": FileList.from_dict(obj["files"]) if obj.get("files") is not None else None,
            "productsStore": Store.from_dict(obj["productsStore"]) if obj.get("productsStore") is not None else None,
            "materialsStore": Store.from_dict(obj["materialsStore"]) if obj.get("materialsStore") is not None else None,
            "products": ProcessingProductList.from_dict(obj["products"]) if obj.get("products") is not None else None,
            "materials": ProcessingMaterialList.from_dict(obj["materials"]) if obj.get("materials") is not None else None,
            "quantity": obj.get("quantity"),
            "processingSum": obj.get("processingSum")
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

from moysklad_remap_12_sdk.models.processing_order import ProcessingOrder
# TODO: Rewrite to not use raise_errors
Processing.model_rebuild(raise_errors=False)


from moysklad_remap_12_sdk.models.meta import Meta

































from moysklad_remap_12_sdk.models.organization import Organization



from moysklad_remap_12_sdk.models.account import Account



from moysklad_remap_12_sdk.models.processing_plan import ProcessingPlan



from moysklad_remap_12_sdk.models.processing_order import ProcessingOrder



from moysklad_remap_12_sdk.models.project import Project



from moysklad_remap_12_sdk.models.employee import Employee



from moysklad_remap_12_sdk.models.group import Group



from moysklad_remap_12_sdk.models.state import State




from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract


from moysklad_remap_12_sdk.models.file_list import FileList



from moysklad_remap_12_sdk.models.store import Store



from moysklad_remap_12_sdk.models.store import Store



from moysklad_remap_12_sdk.models.processing_product_list import ProcessingProductList



from moysklad_remap_12_sdk.models.processing_material_list import ProcessingMaterialList







