# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.agent import Agent
from moysklad_remap_12_sdk.models.employee import Employee
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.store import Store
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.entity_with_meta import EntityWithMeta

class ProcessingStage(EntityWithMeta):
    """
    Этап производства
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID Этапа производства")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    owner: Optional[Employee] = Field(default=None, description="Метаданные владельца (Сотрудника)")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    group: Optional[Group] = None
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления Этапа производства")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Наименование Этапа производства")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Комментарий Этапа производства")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код Этапа производства", alias="externalCode")
    archived: Optional[StrictBool] = Field(default=None, description="Добавлен ли Этап производства в архив")
    all_performers: Optional[StrictBool] = Field(default=None, description="Признак доступности назначения на этап любого сотрудника", alias="allPerformers")
    distribution_required: Optional[StrictBool] = Field(default=None, description="Признак видимости заданий для исполнителей в веб-приложении МойСклад Производство", alias="distributionRequired")
    performers: Optional[List[Agent]] = Field(default=None, description="Метаданные возможных исполнителей")
    material_store: Optional[Store] = Field(default=None, description="Метаданные склада материалов", alias="materialStore")
    standard_hour_cost: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Стоимость нормо-часа", alias="standardHourCost")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "owner", "shared", "group", "updated", "name", "description", "externalCode", "archived", "allPerformers", "distributionRequired", "performers", "materialStore", "standardHourCost"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/processingstage" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="processingstage",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProcessingStage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        _items = []
        if self.performers:
            for _item_performers in self.performers:
                if _item_performers:
                    _items.append(_item_performers.to_dict())
            _dict['performers'] = _items
        if self.material_store:
            _dict['materialStore'] = self.material_store.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        if self.performers is None and "performers" in self.model_fields_set:
            _dict['performers'] = None

        if self.material_store is None and "material_store" in self.model_fields_set:
            _dict['materialStore'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProcessingStage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "shared": obj.get("shared"),
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "updated": obj.get("updated"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "externalCode": obj.get("externalCode"),
            "archived": obj.get("archived"),
            "allPerformers": obj.get("allPerformers"),
            "distributionRequired": obj.get("distributionRequired"),
            "performers": [Agent.from_dict(_item) for _item in obj["performers"]] if obj.get("performers") is not None else None,
            "materialStore": Store.from_dict(obj["materialStore"]) if obj.get("materialStore") is not None else None,
            "standardHourCost": obj.get("standardHourCost")
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj



from moysklad_remap_12_sdk.models.meta import Meta







from moysklad_remap_12_sdk.models.employee import Employee





from moysklad_remap_12_sdk.models.group import Group


















from moysklad_remap_12_sdk.models.agent import Agent


from moysklad_remap_12_sdk.models.store import Store





