# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.pack import Pack
from moysklad_remap_12_sdk.models.product_marker import ProductMarker
from moysklad_remap_12_sdk.models.store_slot import StoreSlot
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.entity_with_meta import EntityWithMeta

class PurchaseReturnPosition(EntityWithMeta):
    """
    Позиция Возврата поставщику
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID позиции")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    assortment: Optional[ProductMarker] = Field(default=None, description="Метаданные товара/услуги/партии/модификации, которую представляет собой позиция")
    discount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Процент скидки или наценки")
    pack: Optional[Pack] = Field(default=None, description="Упаковка Товара")
    price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Цена товара/услуги в копейках")
    quantity: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Количество товаров данного вида в позиции")
    slot: Optional[StoreSlot] = Field(default=None, description="Ячейка на складе")
    things: Optional[List[StrictStr]] = Field(default=None, description="Серийные номера. Игнорируется, если товар позиции не на серийном учёте; иначе количество единиц в позиции совпадает с числом переданных серийных номеров. ")
    vat: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, description="НДС, которым облагается текущая позиция")
    vat_enabled: Optional[StrictBool] = Field(default=None, description="Включён ли НДС для позиции. Пара `(vat = 0, vatEnabled = false)` соответствует НДС «без НДС»; `(vat = 0, vatEnabled = true)` — НДС 0%. ", alias="vatEnabled")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "assortment", "discount", "pack", "price", "quantity", "slot", "things", "vat", "vatEnabled"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        parentId: str,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/purchasereturn" + "/" + parentId + "/positions" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="purchasereturnposition",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PurchaseReturnPosition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.assortment:
            _dict['assortment'] = self.assortment.to_dict()
        if self.pack:
            _dict['pack'] = self.pack.to_dict()
        if self.slot:
            _dict['slot'] = self.slot.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.pack is None and "pack" in self.model_fields_set:
            _dict['pack'] = None

        if self.slot is None and "slot" in self.model_fields_set:
            _dict['slot'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PurchaseReturnPosition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "assortment": ProductMarker.from_dict(obj["assortment"]) if obj.get("assortment") is not None else None,
            "discount": obj.get("discount"),
            "pack": Pack.from_dict(obj["pack"]) if obj.get("pack") is not None else None,
            "price": obj.get("price"),
            "quantity": obj.get("quantity"),
            "slot": StoreSlot.from_dict(obj["slot"]) if obj.get("slot") is not None else None,
            "things": obj.get("things"),
            "vat": obj.get("vat"),
            "vatEnabled": obj.get("vatEnabled")
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj



from moysklad_remap_12_sdk.models.meta import Meta







from moysklad_remap_12_sdk.models.product_marker import ProductMarker





from moysklad_remap_12_sdk.models.pack import Pack







from moysklad_remap_12_sdk.models.store_slot import StoreSlot









