# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from moysklad_remap_12_sdk.models.employee import Employee
from typing import Optional, Set
from typing_extensions import Self

class ReportProfitByEmployee(BaseModel):
    """
    Строка отчета «Прибыльность по сотрудникам»
    """ # noqa: E501
    employee: Optional[Employee] = None
    margin: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Рентабельность")
    sales_margin: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Рентабельность продаж", alias="salesMargin")
    profit: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Прибыль")
    return_avg_check: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Средний чек возврата", alias="returnAvgCheck")
    return_cost_sum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма себестоимостей возвратов в копейках", alias="returnCostSum")
    return_count: Optional[StrictInt] = Field(default=None, description="Количество возвратов", alias="returnCount")
    return_sum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма возвратов", alias="returnSum")
    sales_avg_check: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Средний чек продаж", alias="salesAvgCheck")
    sales_count: Optional[StrictInt] = Field(default=None, description="Количество продаж", alias="salesCount")
    sell_cost_sum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма себестоимостей продаж в копейках", alias="sellCostSum")
    sell_sum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма продаж", alias="sellSum")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["employee", "margin", "salesMargin", "profit", "returnAvgCheck", "returnCostSum", "returnCount", "returnSum", "salesAvgCheck", "salesCount", "sellCostSum", "sellSum"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReportProfitByEmployee from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.employee:
            _dict['employee'] = self.employee.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReportProfitByEmployee from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "employee": Employee.from_dict(obj["employee"]) if obj.get("employee") is not None else None,
            "margin": obj.get("margin"),
            "salesMargin": obj.get("salesMargin"),
            "profit": obj.get("profit"),
            "returnAvgCheck": obj.get("returnAvgCheck"),
            "returnCostSum": obj.get("returnCostSum"),
            "returnCount": obj.get("returnCount"),
            "returnSum": obj.get("returnSum"),
            "salesAvgCheck": obj.get("salesAvgCheck"),
            "salesCount": obj.get("salesCount"),
            "sellCostSum": obj.get("sellCostSum"),
            "sellSum": obj.get("sellSum")
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj



from moysklad_remap_12_sdk.models.employee import Employee

























