# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.account import Account
from moysklad_remap_12_sdk.models.agent import Agent
from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract
from moysklad_remap_12_sdk.models.contract import Contract
from moysklad_remap_12_sdk.models.employee import Employee
from moysklad_remap_12_sdk.models.file_list import FileList
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.organization import Organization
from moysklad_remap_12_sdk.models.retail_shift_cheque import RetailShiftCheque
from moysklad_remap_12_sdk.models.retail_shift_operation import RetailShiftOperation
from moysklad_remap_12_sdk.models.retail_shift_payment_operation import RetailShiftPaymentOperation
from moysklad_remap_12_sdk.models.retail_store import RetailStore
from moysklad_remap_12_sdk.models.store import Store
from typing import Optional, Set
from typing_extensions import Self

class RetailShift(BaseModel):
    """
    Розничная смена
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID Розничной смены")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Наименование смены")
    moment: Optional[StrictStr] = Field(default=None, description="Дата смены")
    retail_store: Optional[RetailStore] = Field(default=None, description="Метаданные точки продаж", alias="retailStore")
    payments: Optional[List[RetailShiftPaymentsInner]] = Field(default=None, description="Связанные платежи")
    acquire: Optional[Agent] = Field(default=None, description="Метаданные Банка-эквайера по операциям по карте")
    agent_account: Optional[Account] = Field(default=None, description="Метаданные счета контрагента", alias="agentAccount")
    attributes: Optional[List[AttributeAbstract]] = Field(default=None, description="Коллекция метаданных доп. полей")
    bank_comission: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма комиссии эквайера за проведение безналичных платежей по банковской карте", alias="bankComission")
    bank_percent: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]] = Field(default=None, description="Комиссия банка-эквайера по операциям по карте (в процентах)", alias="bankPercent")
    cheque: Optional[RetailShiftCheque] = Field(default=None, description="Информация о смене ККТ")
    close_date: Optional[StrictStr] = Field(default=None, description="Дата закрытия смены", alias="closeDate")
    contract: Optional[Contract] = Field(default=None, description="Метаданные договора")
    created: Optional[StrictStr] = Field(default=None, description="Дата создания")
    deleted: Optional[StrictStr] = Field(default=None, description="Момент последнего удаления Розничной смены")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Комментарий Розничной смены")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код Розничной смены", alias="externalCode")
    files: Optional[FileList] = Field(default=None, description="Метаданные массива Файлов")
    group: Optional[Group] = Field(default=None, description="Отдел сотрудника")
    operations: Optional[List[RetailShiftOperation]] = Field(default=None, description="Связанные операции. Допустимые типы по `meta.type`: retaildemand, retailsalesreturn, retaildrawercashin, retaildrawercashout, prepayment, prepaymentreturn. ")
    organization: Optional[Organization] = None
    organization_account: Optional[Account] = Field(default=None, description="Метаданные счета юрлица", alias="organizationAccount")
    owner: Optional[Employee] = Field(default=None, description="Владелец (Сотрудник)")
    payment_operations: Optional[List[RetailShiftPaymentOperation]] = Field(default=None, description="Коллекция метаданных платежных операций", alias="paymentOperations")
    printed: Optional[StrictBool] = Field(default=None, description="Напечатан ли документ")
    proceeds_cash: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Выручка наличными", alias="proceedsCash")
    proceeds_no_cash: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Выручка безнал", alias="proceedsNoCash")
    published: Optional[StrictBool] = Field(default=None, description="Опубликован ли документ")
    qr_acquire: Optional[Agent] = Field(default=None, description="Метаданные Банка-эквайера по операциям по QR-коду", alias="qrAcquire")
    qr_bank_comission: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма комиссии эквайера за проведение безналичных платежей по QR-коду", alias="qrBankComission")
    qr_bank_percent: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]] = Field(default=None, description="Комиссия банка-эквайера по операция по QR-коду (в процентах)", alias="qrBankPercent")
    received_cash: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Получено наличными", alias="receivedCash")
    received_no_cash: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Получено безнал", alias="receivedNoCash")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    store: Optional[Store] = None
    sync_id: Optional[StrictStr] = Field(default=None, description="ID синхронизации", alias="syncId")
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления Розничной смены")
    vat_enabled: Optional[StrictBool] = Field(default=None, description="Учитывается ли НДС", alias="vatEnabled")
    vat_included: Optional[StrictBool] = Field(default=None, description="Включен ли НДС в цену", alias="vatIncluded")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "name", "moment", "retailStore", "payments", "acquire", "agentAccount", "attributes", "bankComission", "bankPercent", "cheque", "closeDate", "contract", "created", "deleted", "description", "externalCode", "files", "group", "operations", "organization", "organizationAccount", "owner", "paymentOperations", "printed", "proceedsCash", "proceedsNoCash", "published", "qrAcquire", "qrBankComission", "qrBankPercent", "receivedCash", "receivedNoCash", "shared", "store", "syncId", "updated", "vatEnabled", "vatIncluded"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/retailshift" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="retailshift",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetailShift from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.retail_store:
            _dict['retailStore'] = self.retail_store.to_dict()
        _items = []
        if self.payments:
            for _item_payments in self.payments:
                if _item_payments:
                    _items.append(_item_payments.to_dict())
            _dict['payments'] = _items
        if self.acquire:
            _dict['acquire'] = self.acquire.to_dict()
        if self.agent_account:
            _dict['agentAccount'] = self.agent_account.to_dict()
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        if self.cheque:
            _dict['cheque'] = self.cheque.to_dict()
        if self.contract:
            _dict['contract'] = self.contract.to_dict()
        if self.files:
            _dict['files'] = self.files.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        _items = []
        if self.operations:
            for _item_operations in self.operations:
                if _item_operations:
                    _items.append(_item_operations.to_dict())
            _dict['operations'] = _items
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        if self.organization_account:
            _dict['organizationAccount'] = self.organization_account.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        _items = []
        if self.payment_operations:
            for _item_payment_operations in self.payment_operations:
                if _item_payment_operations:
                    _items.append(_item_payment_operations.to_dict())
            _dict['paymentOperations'] = _items
        if self.qr_acquire:
            _dict['qrAcquire'] = self.qr_acquire.to_dict()
        if self.store:
            _dict['store'] = self.store.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.retail_store is None and "retail_store" in self.model_fields_set:
            _dict['retailStore'] = None

        if self.payments is None and "payments" in self.model_fields_set:
            _dict['payments'] = None

        if self.acquire is None and "acquire" in self.model_fields_set:
            _dict['acquire'] = None

        if self.agent_account is None and "agent_account" in self.model_fields_set:
            _dict['agentAccount'] = None

        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        if self.cheque is None and "cheque" in self.model_fields_set:
            _dict['cheque'] = None

        if self.close_date is None and "close_date" in self.model_fields_set:
            _dict['closeDate'] = None

        if self.contract is None and "contract" in self.model_fields_set:
            _dict['contract'] = None

        if self.deleted is None and "deleted" in self.model_fields_set:
            _dict['deleted'] = None

        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        if self.files is None and "files" in self.model_fields_set:
            _dict['files'] = None

        if self.operations is None and "operations" in self.model_fields_set:
            _dict['operations'] = None

        if self.organization_account is None and "organization_account" in self.model_fields_set:
            _dict['organizationAccount'] = None

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.payment_operations is None and "payment_operations" in self.model_fields_set:
            _dict['paymentOperations'] = None

        if self.qr_acquire is None and "qr_acquire" in self.model_fields_set:
            _dict['qrAcquire'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetailShift from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "name": obj.get("name"),
            "moment": obj.get("moment"),
            "retailStore": RetailStore.from_dict(obj["retailStore"]) if obj.get("retailStore") is not None else None,
            "payments": [RetailShiftPaymentsInner.from_dict(_item) for _item in obj["payments"]] if obj.get("payments") is not None else None,
            "acquire": Agent.from_dict(obj["acquire"]) if obj.get("acquire") is not None else None,
            "agentAccount": Account.from_dict(obj["agentAccount"]) if obj.get("agentAccount") is not None else None,
            "attributes": [AttributeAbstract.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "bankComission": obj.get("bankComission"),
            "bankPercent": obj.get("bankPercent"),
            "cheque": RetailShiftCheque.from_dict(obj["cheque"]) if obj.get("cheque") is not None else None,
            "closeDate": obj.get("closeDate"),
            "contract": Contract.from_dict(obj["contract"]) if obj.get("contract") is not None else None,
            "created": obj.get("created"),
            "deleted": obj.get("deleted"),
            "description": obj.get("description"),
            "externalCode": obj.get("externalCode"),
            "files": FileList.from_dict(obj["files"]) if obj.get("files") is not None else None,
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "operations": [RetailShiftOperation.from_dict(_item) for _item in obj["operations"]] if obj.get("operations") is not None else None,
            "organization": Organization.from_dict(obj["organization"]) if obj.get("organization") is not None else None,
            "organizationAccount": Account.from_dict(obj["organizationAccount"]) if obj.get("organizationAccount") is not None else None,
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "paymentOperations": [RetailShiftPaymentOperation.from_dict(_item) for _item in obj["paymentOperations"]] if obj.get("paymentOperations") is not None else None,
            "printed": obj.get("printed"),
            "proceedsCash": obj.get("proceedsCash"),
            "proceedsNoCash": obj.get("proceedsNoCash"),
            "published": obj.get("published"),
            "qrAcquire": Agent.from_dict(obj["qrAcquire"]) if obj.get("qrAcquire") is not None else None,
            "qrBankComission": obj.get("qrBankComission"),
            "qrBankPercent": obj.get("qrBankPercent"),
            "receivedCash": obj.get("receivedCash"),
            "receivedNoCash": obj.get("receivedNoCash"),
            "shared": obj.get("shared"),
            "store": Store.from_dict(obj["store"]) if obj.get("store") is not None else None,
            "syncId": obj.get("syncId"),
            "updated": obj.get("updated"),
            "vatEnabled": obj.get("vatEnabled"),
            "vatIncluded": obj.get("vatIncluded")
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

from moysklad_remap_12_sdk.models.retail_shift_payments_inner import RetailShiftPaymentsInner
# TODO: Rewrite to not use raise_errors
RetailShift.model_rebuild(raise_errors=False)


from moysklad_remap_12_sdk.models.meta import Meta











from moysklad_remap_12_sdk.models.retail_store import RetailStore




from moysklad_remap_12_sdk.models.retail_shift_payments_inner import RetailShiftPaymentsInner


from moysklad_remap_12_sdk.models.agent import Agent



from moysklad_remap_12_sdk.models.account import Account




from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract






from moysklad_remap_12_sdk.models.retail_shift_cheque import RetailShiftCheque





from moysklad_remap_12_sdk.models.contract import Contract











from moysklad_remap_12_sdk.models.file_list import FileList



from moysklad_remap_12_sdk.models.group import Group




from moysklad_remap_12_sdk.models.retail_shift_operation import RetailShiftOperation


from moysklad_remap_12_sdk.models.organization import Organization



from moysklad_remap_12_sdk.models.account import Account



from moysklad_remap_12_sdk.models.employee import Employee




from moysklad_remap_12_sdk.models.retail_shift_payment_operation import RetailShiftPaymentOperation










from moysklad_remap_12_sdk.models.agent import Agent













from moysklad_remap_12_sdk.models.store import Store











