# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from moysklad_remap_12_sdk.models.account import Account
from moysklad_remap_12_sdk.models.agent import Agent
from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract
from moysklad_remap_12_sdk.models.contract import Contract
from moysklad_remap_12_sdk.models.currency_rate import CurrencyRate
from moysklad_remap_12_sdk.models.employee import Employee
from moysklad_remap_12_sdk.models.group import Group
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.organization import Organization
from moysklad_remap_12_sdk.models.retail_demand import RetailDemand
from moysklad_remap_12_sdk.models.retail_sales_return_position_list import RetailSalesReturnPositionList
from moysklad_remap_12_sdk.models.retail_shift import RetailShift
from moysklad_remap_12_sdk.models.retail_store import RetailStore
from moysklad_remap_12_sdk.models.state import State
from moysklad_remap_12_sdk.models.store import Store
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.retail_shift_operation import RetailShiftOperation

class RetailShiftOperationRetailSalesReturn(RetailShiftOperation):
    """
    Розничный возврат
    """ # noqa: E501
    meta: Optional[Meta] = None
    id: Optional[StrictStr] = Field(default=None, description="ID Розничного возврата")
    account_id: Optional[StrictStr] = Field(default=None, description="ID учетной записи", alias="accountId")
    agent: Optional[Agent] = Field(default=None, description="Метаданные контрагента")
    agent_account: Optional[Account] = Field(default=None, description="Метаданные счета контрагента", alias="agentAccount")
    applicable: Optional[StrictBool] = Field(default=None, description="Отметка о проведении")
    attributes: Optional[List[AttributeAbstract]] = Field(default=None, description="Коллекция метаданных доп. полей")
    cash_sum: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Оплачено наличными", alias="cashSum")
    code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Код Розничного возврата")
    contract: Optional[Contract] = Field(default=None, description="Метаданные договора")
    created: Optional[StrictStr] = Field(default=None, description="Дата создания")
    deleted: Optional[StrictStr] = Field(default=None, description="Момент последнего удаления Розничного возврата")
    demand: Optional[RetailDemand] = Field(default=None, description="Метаданные связанной Розничной продажи")
    description: Optional[Annotated[str, Field(strict=True, max_length=4096)]] = Field(default=None, description="Комментарий Розничного возврата")
    external_code: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Внешний код Розничного возврата", alias="externalCode")
    group: Optional[Group] = None
    moment: Optional[StrictStr] = Field(default=None, description="Дата документа")
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, description="Наименование Розничного возврата")
    no_cash_sum: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Оплачено картой", alias="noCashSum")
    organization: Optional[Organization] = None
    organization_account: Optional[Account] = Field(default=None, description="Метаданные счета юрлица", alias="organizationAccount")
    owner: Optional[Employee] = Field(default=None, description="Владелец (Сотрудник)")
    positions: Optional[RetailSalesReturnPositionList] = None
    printed: Optional[StrictBool] = Field(default=None, description="Напечатан ли документ")
    published: Optional[StrictBool] = Field(default=None, description="Опубликован ли документ")
    qr_sum: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Оплачено по QR-коду", alias="qrSum")
    rate: Optional[CurrencyRate] = Field(default=None, alias="rate")
    retail_shift: Optional[RetailShift] = Field(default=None, alias="retailShift")
    retail_store: Optional[RetailStore] = Field(default=None, alias="retailStore")
    shared: Optional[StrictBool] = Field(default=None, description="Общий доступ")
    state: Optional[State] = Field(default=None, description="Метаданные статуса Розничного возврата")
    store: Optional[Store] = None
    sum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма Розничного возврата в копейках")
    sync_id: Optional[StrictStr] = Field(default=None, description="ID синхронизации", alias="syncId")
    tax_system: Optional[StrictStr] = Field(default=None, description="Код системы налогообложения. Известные значения описаны в TaxSystem", alias="taxSystem")
    updated: Optional[StrictStr] = Field(default=None, description="Момент последнего обновления Розничного возврата")
    vat_enabled: Optional[StrictBool] = Field(default=None, description="Учитывается ли НДС", alias="vatEnabled")
    vat_included: Optional[StrictBool] = Field(default=None, description="Включен ли НДС в цену", alias="vatIncluded")
    vat_sum: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Сумма НДС", alias="vatSum")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "id", "accountId", "agent", "agentAccount", "applicable", "attributes", "cashSum", "code", "contract", "created", "deleted", "demand", "description", "externalCode", "group", "moment", "name", "noCashSum", "organization", "organizationAccount", "owner", "positions", "printed", "published", "qrSum", "rate", "retailShift", "retailStore", "shared", "state", "store", "sum", "syncId", "taxSystem", "updated", "vatEnabled", "vatIncluded", "vatSum"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetailShiftOperationRetailSalesReturn from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        if self.agent:
            _dict['agent'] = self.agent.to_dict()
        if self.agent_account:
            _dict['agentAccount'] = self.agent_account.to_dict()
        _items = []
        if self.attributes:
            for _item_attributes in self.attributes:
                if _item_attributes:
                    _items.append(_item_attributes.to_dict())
            _dict['attributes'] = _items
        if self.contract:
            _dict['contract'] = self.contract.to_dict()
        if self.demand:
            _dict['demand'] = self.demand.to_dict()
        if self.group:
            _dict['group'] = self.group.to_dict()
        if self.organization:
            _dict['organization'] = self.organization.to_dict()
        if self.organization_account:
            _dict['organizationAccount'] = self.organization_account.to_dict()
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        if self.positions:
            _dict['positions'] = self.positions.to_dict()
        if self.rate:
            _dict['rate'] = self.rate.to_dict()
        if self.retail_shift:
            _dict['retailShift'] = self.retail_shift.to_dict()
        if self.retail_store:
            _dict['retailStore'] = self.retail_store.to_dict()
        if self.state:
            _dict['state'] = self.state.to_dict()
        if self.store:
            _dict['store'] = self.store.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.agent_account is None and "agent_account" in self.model_fields_set:
            _dict['agentAccount'] = None

        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        if self.contract is None and "contract" in self.model_fields_set:
            _dict['contract'] = None

        if self.demand is None and "demand" in self.model_fields_set:
            _dict['demand'] = None

        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        if self.organization_account is None and "organization_account" in self.model_fields_set:
            _dict['organizationAccount'] = None

        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetailShiftOperationRetailSalesReturn from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "id": obj.get("id"),
            "accountId": obj.get("accountId"),
            "agent": Agent.from_dict(obj["agent"]) if obj.get("agent") is not None else None,
            "agentAccount": Account.from_dict(obj["agentAccount"]) if obj.get("agentAccount") is not None else None,
            "applicable": obj.get("applicable"),
            "attributes": [AttributeAbstract.from_dict(_item) for _item in obj["attributes"]] if obj.get("attributes") is not None else None,
            "cashSum": obj.get("cashSum"),
            "code": obj.get("code"),
            "contract": Contract.from_dict(obj["contract"]) if obj.get("contract") is not None else None,
            "created": obj.get("created"),
            "deleted": obj.get("deleted"),
            "demand": RetailDemand.from_dict(obj["demand"]) if obj.get("demand") is not None else None,
            "description": obj.get("description"),
            "externalCode": obj.get("externalCode"),
            "group": Group.from_dict(obj["group"]) if obj.get("group") is not None else None,
            "moment": obj.get("moment"),
            "name": obj.get("name"),
            "noCashSum": obj.get("noCashSum"),
            "organization": Organization.from_dict(obj["organization"]) if obj.get("organization") is not None else None,
            "organizationAccount": Account.from_dict(obj["organizationAccount"]) if obj.get("organizationAccount") is not None else None,
            "owner": Employee.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "positions": RetailSalesReturnPositionList.from_dict(obj["positions"]) if obj.get("positions") is not None else None,
            "printed": obj.get("printed"),
            "published": obj.get("published"),
            "qrSum": obj.get("qrSum"),
            "rate": CurrencyRate.from_dict(obj["rate"]) if obj.get("rate") is not None else None,
            "retailShift": RetailShift.from_dict(obj["retailShift"]) if obj.get("retailShift") is not None else None,
            "retailStore": RetailStore.from_dict(obj["retailStore"]) if obj.get("retailStore") is not None else None,
            "shared": obj.get("shared"),
            "state": State.from_dict(obj["state"]) if obj.get("state") is not None else None,
            "store": Store.from_dict(obj["store"]) if obj.get("store") is not None else None,
            "sum": obj.get("sum"),
            "syncId": obj.get("syncId"),
            "taxSystem": obj.get("taxSystem"),
            "updated": obj.get("updated"),
            "vatEnabled": obj.get("vatEnabled"),
            "vatIncluded": obj.get("vatIncluded"),
            "vatSum": obj.get("vatSum")
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj



from moysklad_remap_12_sdk.models.meta import Meta







from moysklad_remap_12_sdk.models.agent import Agent



from moysklad_remap_12_sdk.models.account import Account






from moysklad_remap_12_sdk.models.attribute_abstract import AttributeAbstract






from moysklad_remap_12_sdk.models.contract import Contract







from moysklad_remap_12_sdk.models.retail_demand import RetailDemand







from moysklad_remap_12_sdk.models.group import Group









from moysklad_remap_12_sdk.models.organization import Organization



from moysklad_remap_12_sdk.models.account import Account



from moysklad_remap_12_sdk.models.employee import Employee



from moysklad_remap_12_sdk.models.retail_sales_return_position_list import RetailSalesReturnPositionList









from moysklad_remap_12_sdk.models.currency_rate import CurrencyRate



from moysklad_remap_12_sdk.models.retail_shift import RetailShift



from moysklad_remap_12_sdk.models.retail_store import RetailStore





from moysklad_remap_12_sdk.models.state import State



from moysklad_remap_12_sdk.models.store import Store

















