# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from moysklad_remap_12_sdk.models.permissions import Permissions
from moysklad_remap_12_sdk.models.script_permissions import ScriptPermissions
from moysklad_remap_12_sdk.models.script_template_permissions import ScriptTemplatePermissions
from typing import Optional, Set
from typing_extensions import Self

class RolePermissions(BaseModel):
    """
    Права роли. В JSON передаются объектом, где ключи — названия пермиссий, значения — Boolean или объекты прав сущностей. Для currency, country, taxrate и uom право view неизменяемо и равно ALL; попытка изменить его приводит к ошибке. 
    """ # noqa: E501
    api_request: Optional[StrictBool] = Field(default=None, description="Доступ по АПИ", alias="apiRequest")
    account_delete: Optional[StrictBool] = Field(default=None, description="Удалять аккаунт", alias="accountDelete")
    delete_from_recycle_bin: Optional[StrictBool] = Field(default=None, description="Очищать корзину", alias="deleteFromRecycleBin")
    edit_currency_rate_of_document: Optional[StrictBool] = Field(default=None, description="Редактировать курс валюты документа", alias="editCurrencyRateOfDocument")
    edit_document_templates: Optional[StrictBool] = Field(default=None, description="Редактировать шаблоны документов и отчетов", alias="editDocumentTemplates")
    edit_documents_of_restricted_period: Optional[StrictBool] = Field(default=None, description="Редактировать документы закрытого периода", alias="editDocumentsOfRestrictedPeriod")
    export_data: Optional[StrictBool] = Field(default=None, description="Экспортировать данные", alias="exportData")
    import_data: Optional[StrictBool] = Field(default=None, description="Импортировать данные", alias="importData")
    listen_calls: Optional[StrictBool] = Field(default=None, description="Прослушивание звонков", alias="listenCalls")
    online_shops: Optional[StrictBool] = Field(default=None, description="Интернет магазины", alias="onlineShops")
    owner_assign: Optional[StrictBool] = Field(default=None, description="Передавать владение аккаунтом", alias="ownerAssign")
    owner_data_update: Optional[StrictBool] = Field(default=None, description="Редактировать данные владельца", alias="ownerDataUpdate")
    purchase_control: Optional[StrictBool] = Field(default=None, description="Управление закупками", alias="purchaseControl")
    restore_from_recycle_bin: Optional[StrictBool] = Field(default=None, description="Восстанавливать документы из корзины", alias="restoreFromRecycleBin")
    send_email: Optional[StrictBool] = Field(default=None, description="Отправлять почту", alias="sendEmail")
    subscription_control: Optional[StrictBool] = Field(default=None, description="Управление подпиской", alias="subscriptionControl")
    view_audit: Optional[StrictBool] = Field(default=None, description="Просматривать аудит", alias="viewAudit")
    view_cash_flow: Optional[StrictBool] = Field(default=None, description="Просматривать движение денежных средств", alias="viewCashFlow")
    view_commission_goods: Optional[StrictBool] = Field(default=None, description="Просматривать товары на реализации", alias="viewCommissionGoods")
    view_company_crm: Optional[StrictBool] = Field(default=None, description="Просматривать показатели", alias="viewCompanyCRM")
    view_customer_balance_list: Optional[StrictBool] = Field(default=None, description="Просматривать взаиморасчеты", alias="viewCustomerBalanceList")
    view_dashboard: Optional[StrictBool] = Field(default=None, description="Просматривать показатели", alias="viewDashboard")
    view_money_dashboard: Optional[StrictBool] = Field(default=None, description="Видеть остатки денег", alias="viewMoneyDashboard")
    view_product_cost_and_profit: Optional[StrictBool] = Field(default=None, description="Видеть себестоимость, цену закупки и прибыль товаров", alias="viewProductCostAndProfit")
    view_profit_and_loss: Optional[StrictBool] = Field(default=None, description="Просматривать прибыль и убытки", alias="viewProfitAndLoss")
    view_purchase_funnel: Optional[StrictBool] = Field(default=None, description="Просматривать воронку продаж", alias="viewPurchaseFunnel")
    view_recycle_bin: Optional[StrictBool] = Field(default=None, description="Просматривать корзину", alias="viewRecycleBin")
    view_sale_profit: Optional[StrictBool] = Field(default=None, description="Просматривать прибыльность", alias="viewSaleProfit")
    view_serial_numbers: Optional[StrictBool] = Field(default=None, description="Просматривать серийные номера", alias="viewSerialNumbers")
    view_stock_report: Optional[StrictBool] = Field(default=None, description="Просматривать остатки по товарам", alias="viewStockReport")
    view_turnover: Optional[StrictBool] = Field(default=None, description="Просматривать обороты", alias="viewTurnover")
    gtin_list: Optional[Permissions] = Field(default=None, alias="GTINList")
    account_adjustment: Optional[Permissions] = Field(default=None, alias="accountAdjustment")
    bonus_transaction: Optional[Permissions] = Field(default=None, alias="bonusTransaction")
    cash_in: Optional[Permissions] = Field(default=None, alias="cashIn")
    cash_out: Optional[Permissions] = Field(default=None, alias="cashOut")
    cashbox_adjustment: Optional[Permissions] = Field(default=None, alias="cashboxAdjustment")
    commission_report_in: Optional[Permissions] = Field(default=None, alias="commissionReportIn")
    commission_report_out: Optional[Permissions] = Field(default=None, alias="commissionReportOut")
    company: Optional[Permissions] = None
    contract: Optional[Permissions] = None
    counterparty_adjustment: Optional[Permissions] = Field(default=None, alias="counterpartyAdjustment")
    country: Optional[Permissions] = None
    crpt_cancellation: Optional[Permissions] = Field(default=None, alias="crptCancellation")
    crpt_package_creation: Optional[Permissions] = Field(default=None, alias="crptPackageCreation")
    crpt_package_disaggregation: Optional[Permissions] = Field(default=None, alias="crptPackageDisaggregation")
    crpt_package_item_removal: Optional[Permissions] = Field(default=None, alias="crptPackageItemRemoval")
    currency: Optional[Permissions] = None
    custom_entity: Optional[Permissions] = Field(default=None, alias="customEntity")
    customer_order: Optional[Permissions] = Field(default=None, alias="customerOrder")
    demand: Optional[Permissions] = None
    emission_order: Optional[Permissions] = Field(default=None, alias="emissionOrder")
    utilization_report: Optional[Permissions] = Field(default=None, alias="utilizationReport")
    atk_aggregation: Optional[Permissions] = Field(default=None, alias="atkAggregation")
    retire_order_osu: Optional[Permissions] = Field(default=None, alias="retireOrderOSU")
    employee: Optional[Permissions] = None
    enroll_order: Optional[Permissions] = Field(default=None, alias="enrollOrder")
    enroll_return: Optional[Permissions] = Field(default=None, alias="enrollReturn")
    enter: Optional[Permissions] = None
    expenseitem: Optional[Permissions] = None
    facture_in: Optional[Permissions] = Field(default=None, alias="factureIn")
    facture_out: Optional[Permissions] = Field(default=None, alias="factureOut")
    good: Optional[Permissions] = None
    internal_order: Optional[Permissions] = Field(default=None, alias="internalOrder")
    inventory: Optional[Permissions] = None
    invoice_in: Optional[Permissions] = Field(default=None, alias="invoiceIn")
    invoice_out: Optional[Permissions] = Field(default=None, alias="invoiceOut")
    loss: Optional[Permissions] = None
    move: Optional[Permissions] = None
    my_company: Optional[Permissions] = Field(default=None, alias="myCompany")
    payment_in: Optional[Permissions] = Field(default=None, alias="paymentIn")
    payment_out: Optional[Permissions] = Field(default=None, alias="paymentOut")
    prepayment: Optional[Permissions] = None
    prepayment_return: Optional[Permissions] = Field(default=None, alias="prepaymentReturn")
    price_list: Optional[Permissions] = Field(default=None, alias="priceList")
    processing: Optional[Permissions] = None
    processing_order: Optional[Permissions] = Field(default=None, alias="processingOrder")
    processing_plan: Optional[Permissions] = Field(default=None, alias="processingPlan")
    processing_stage: Optional[Permissions] = Field(default=None, alias="processingStage")
    processing_process: Optional[Permissions] = Field(default=None, alias="processingProcess")
    production_task: Optional[Permissions] = Field(default=None, alias="productionTask")
    production_stage_completion: Optional[Permissions] = Field(default=None, alias="productionStageCompletion")
    project: Optional[Permissions] = None
    purchase_order: Optional[Permissions] = Field(default=None, alias="purchaseOrder")
    purchase_return: Optional[Permissions] = Field(default=None, alias="purchaseReturn")
    remains_order: Optional[Permissions] = Field(default=None, alias="remainsOrder")
    remarking_order: Optional[Permissions] = Field(default=None, alias="remarkingOrder")
    retail_demand: Optional[Permissions] = Field(default=None, alias="retailDemand")
    retail_drawer_cash_in: Optional[Permissions] = Field(default=None, alias="retailDrawerCashIn")
    retail_drawer_cash_out: Optional[Permissions] = Field(default=None, alias="retailDrawerCashOut")
    retail_sales_return: Optional[Permissions] = Field(default=None, alias="retailSalesReturn")
    retail_shift: Optional[Permissions] = Field(default=None, alias="retailShift")
    retail_store: Optional[Permissions] = Field(default=None, alias="retailStore")
    retire_order: Optional[Permissions] = Field(default=None, alias="retireOrder")
    sales_return: Optional[Permissions] = Field(default=None, alias="salesReturn")
    sales_channel: Optional[Permissions] = Field(default=None, alias="salesChannel")
    script: Optional[ScriptPermissions] = None
    script_template: Optional[ScriptTemplatePermissions] = Field(default=None, alias="scriptTemplate")
    supply: Optional[Permissions] = None
    taxrate: Optional[Permissions] = None
    tracking_code_list: Optional[Permissions] = Field(default=None, alias="trackingCodeList")
    uom: Optional[Permissions] = None
    warehouse: Optional[Permissions] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiRequest", "accountDelete", "deleteFromRecycleBin", "editCurrencyRateOfDocument", "editDocumentTemplates", "editDocumentsOfRestrictedPeriod", "exportData", "importData", "listenCalls", "onlineShops", "ownerAssign", "ownerDataUpdate", "purchaseControl", "restoreFromRecycleBin", "sendEmail", "subscriptionControl", "viewAudit", "viewCashFlow", "viewCommissionGoods", "viewCompanyCRM", "viewCustomerBalanceList", "viewDashboard", "viewMoneyDashboard", "viewProductCostAndProfit", "viewProfitAndLoss", "viewPurchaseFunnel", "viewRecycleBin", "viewSaleProfit", "viewSerialNumbers", "viewStockReport", "viewTurnover", "GTINList", "accountAdjustment", "bonusTransaction", "cashIn", "cashOut", "cashboxAdjustment", "commissionReportIn", "commissionReportOut", "company", "contract", "counterpartyAdjustment", "country", "crptCancellation", "crptPackageCreation", "crptPackageDisaggregation", "crptPackageItemRemoval", "currency", "customEntity", "customerOrder", "demand", "emissionOrder", "utilizationReport", "atkAggregation", "retireOrderOSU", "employee", "enrollOrder", "enrollReturn", "enter", "expenseitem", "factureIn", "factureOut", "good", "internalOrder", "inventory", "invoiceIn", "invoiceOut", "loss", "move", "myCompany", "paymentIn", "paymentOut", "prepayment", "prepaymentReturn", "priceList", "processing", "processingOrder", "processingPlan", "processingStage", "processingProcess", "productionTask", "productionStageCompletion", "project", "purchaseOrder", "purchaseReturn", "remainsOrder", "remarkingOrder", "retailDemand", "retailDrawerCashIn", "retailDrawerCashOut", "retailSalesReturn", "retailShift", "retailStore", "retireOrder", "salesReturn", "salesChannel", "script", "scriptTemplate", "supply", "taxrate", "trackingCodeList", "uom", "warehouse"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RolePermissions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.gtin_list:
            _dict['GTINList'] = self.gtin_list.to_dict()
        if self.account_adjustment:
            _dict['accountAdjustment'] = self.account_adjustment.to_dict()
        if self.bonus_transaction:
            _dict['bonusTransaction'] = self.bonus_transaction.to_dict()
        if self.cash_in:
            _dict['cashIn'] = self.cash_in.to_dict()
        if self.cash_out:
            _dict['cashOut'] = self.cash_out.to_dict()
        if self.cashbox_adjustment:
            _dict['cashboxAdjustment'] = self.cashbox_adjustment.to_dict()
        if self.commission_report_in:
            _dict['commissionReportIn'] = self.commission_report_in.to_dict()
        if self.commission_report_out:
            _dict['commissionReportOut'] = self.commission_report_out.to_dict()
        if self.company:
            _dict['company'] = self.company.to_dict()
        if self.contract:
            _dict['contract'] = self.contract.to_dict()
        if self.counterparty_adjustment:
            _dict['counterpartyAdjustment'] = self.counterparty_adjustment.to_dict()
        if self.country:
            _dict['country'] = self.country.to_dict()
        if self.crpt_cancellation:
            _dict['crptCancellation'] = self.crpt_cancellation.to_dict()
        if self.crpt_package_creation:
            _dict['crptPackageCreation'] = self.crpt_package_creation.to_dict()
        if self.crpt_package_disaggregation:
            _dict['crptPackageDisaggregation'] = self.crpt_package_disaggregation.to_dict()
        if self.crpt_package_item_removal:
            _dict['crptPackageItemRemoval'] = self.crpt_package_item_removal.to_dict()
        if self.currency:
            _dict['currency'] = self.currency.to_dict()
        if self.custom_entity:
            _dict['customEntity'] = self.custom_entity.to_dict()
        if self.customer_order:
            _dict['customerOrder'] = self.customer_order.to_dict()
        if self.demand:
            _dict['demand'] = self.demand.to_dict()
        if self.emission_order:
            _dict['emissionOrder'] = self.emission_order.to_dict()
        if self.utilization_report:
            _dict['utilizationReport'] = self.utilization_report.to_dict()
        if self.atk_aggregation:
            _dict['atkAggregation'] = self.atk_aggregation.to_dict()
        if self.retire_order_osu:
            _dict['retireOrderOSU'] = self.retire_order_osu.to_dict()
        if self.employee:
            _dict['employee'] = self.employee.to_dict()
        if self.enroll_order:
            _dict['enrollOrder'] = self.enroll_order.to_dict()
        if self.enroll_return:
            _dict['enrollReturn'] = self.enroll_return.to_dict()
        if self.enter:
            _dict['enter'] = self.enter.to_dict()
        if self.expenseitem:
            _dict['expenseitem'] = self.expenseitem.to_dict()
        if self.facture_in:
            _dict['factureIn'] = self.facture_in.to_dict()
        if self.facture_out:
            _dict['factureOut'] = self.facture_out.to_dict()
        if self.good:
            _dict['good'] = self.good.to_dict()
        if self.internal_order:
            _dict['internalOrder'] = self.internal_order.to_dict()
        if self.inventory:
            _dict['inventory'] = self.inventory.to_dict()
        if self.invoice_in:
            _dict['invoiceIn'] = self.invoice_in.to_dict()
        if self.invoice_out:
            _dict['invoiceOut'] = self.invoice_out.to_dict()
        if self.loss:
            _dict['loss'] = self.loss.to_dict()
        if self.move:
            _dict['move'] = self.move.to_dict()
        if self.my_company:
            _dict['myCompany'] = self.my_company.to_dict()
        if self.payment_in:
            _dict['paymentIn'] = self.payment_in.to_dict()
        if self.payment_out:
            _dict['paymentOut'] = self.payment_out.to_dict()
        if self.prepayment:
            _dict['prepayment'] = self.prepayment.to_dict()
        if self.prepayment_return:
            _dict['prepaymentReturn'] = self.prepayment_return.to_dict()
        if self.price_list:
            _dict['priceList'] = self.price_list.to_dict()
        if self.processing:
            _dict['processing'] = self.processing.to_dict()
        if self.processing_order:
            _dict['processingOrder'] = self.processing_order.to_dict()
        if self.processing_plan:
            _dict['processingPlan'] = self.processing_plan.to_dict()
        if self.processing_stage:
            _dict['processingStage'] = self.processing_stage.to_dict()
        if self.processing_process:
            _dict['processingProcess'] = self.processing_process.to_dict()
        if self.production_task:
            _dict['productionTask'] = self.production_task.to_dict()
        if self.production_stage_completion:
            _dict['productionStageCompletion'] = self.production_stage_completion.to_dict()
        if self.project:
            _dict['project'] = self.project.to_dict()
        if self.purchase_order:
            _dict['purchaseOrder'] = self.purchase_order.to_dict()
        if self.purchase_return:
            _dict['purchaseReturn'] = self.purchase_return.to_dict()
        if self.remains_order:
            _dict['remainsOrder'] = self.remains_order.to_dict()
        if self.remarking_order:
            _dict['remarkingOrder'] = self.remarking_order.to_dict()
        if self.retail_demand:
            _dict['retailDemand'] = self.retail_demand.to_dict()
        if self.retail_drawer_cash_in:
            _dict['retailDrawerCashIn'] = self.retail_drawer_cash_in.to_dict()
        if self.retail_drawer_cash_out:
            _dict['retailDrawerCashOut'] = self.retail_drawer_cash_out.to_dict()
        if self.retail_sales_return:
            _dict['retailSalesReturn'] = self.retail_sales_return.to_dict()
        if self.retail_shift:
            _dict['retailShift'] = self.retail_shift.to_dict()
        if self.retail_store:
            _dict['retailStore'] = self.retail_store.to_dict()
        if self.retire_order:
            _dict['retireOrder'] = self.retire_order.to_dict()
        if self.sales_return:
            _dict['salesReturn'] = self.sales_return.to_dict()
        if self.sales_channel:
            _dict['salesChannel'] = self.sales_channel.to_dict()
        if self.script:
            _dict['script'] = self.script.to_dict()
        if self.script_template:
            _dict['scriptTemplate'] = self.script_template.to_dict()
        if self.supply:
            _dict['supply'] = self.supply.to_dict()
        if self.taxrate:
            _dict['taxrate'] = self.taxrate.to_dict()
        if self.tracking_code_list:
            _dict['trackingCodeList'] = self.tracking_code_list.to_dict()
        if self.uom:
            _dict['uom'] = self.uom.to_dict()
        if self.warehouse:
            _dict['warehouse'] = self.warehouse.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RolePermissions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "apiRequest": obj.get("apiRequest"),
            "accountDelete": obj.get("accountDelete"),
            "deleteFromRecycleBin": obj.get("deleteFromRecycleBin"),
            "editCurrencyRateOfDocument": obj.get("editCurrencyRateOfDocument"),
            "editDocumentTemplates": obj.get("editDocumentTemplates"),
            "editDocumentsOfRestrictedPeriod": obj.get("editDocumentsOfRestrictedPeriod"),
            "exportData": obj.get("exportData"),
            "importData": obj.get("importData"),
            "listenCalls": obj.get("listenCalls"),
            "onlineShops": obj.get("onlineShops"),
            "ownerAssign": obj.get("ownerAssign"),
            "ownerDataUpdate": obj.get("ownerDataUpdate"),
            "purchaseControl": obj.get("purchaseControl"),
            "restoreFromRecycleBin": obj.get("restoreFromRecycleBin"),
            "sendEmail": obj.get("sendEmail"),
            "subscriptionControl": obj.get("subscriptionControl"),
            "viewAudit": obj.get("viewAudit"),
            "viewCashFlow": obj.get("viewCashFlow"),
            "viewCommissionGoods": obj.get("viewCommissionGoods"),
            "viewCompanyCRM": obj.get("viewCompanyCRM"),
            "viewCustomerBalanceList": obj.get("viewCustomerBalanceList"),
            "viewDashboard": obj.get("viewDashboard"),
            "viewMoneyDashboard": obj.get("viewMoneyDashboard"),
            "viewProductCostAndProfit": obj.get("viewProductCostAndProfit"),
            "viewProfitAndLoss": obj.get("viewProfitAndLoss"),
            "viewPurchaseFunnel": obj.get("viewPurchaseFunnel"),
            "viewRecycleBin": obj.get("viewRecycleBin"),
            "viewSaleProfit": obj.get("viewSaleProfit"),
            "viewSerialNumbers": obj.get("viewSerialNumbers"),
            "viewStockReport": obj.get("viewStockReport"),
            "viewTurnover": obj.get("viewTurnover"),
            "GTINList": Permissions.from_dict(obj["GTINList"]) if obj.get("GTINList") is not None else None,
            "accountAdjustment": Permissions.from_dict(obj["accountAdjustment"]) if obj.get("accountAdjustment") is not None else None,
            "bonusTransaction": Permissions.from_dict(obj["bonusTransaction"]) if obj.get("bonusTransaction") is not None else None,
            "cashIn": Permissions.from_dict(obj["cashIn"]) if obj.get("cashIn") is not None else None,
            "cashOut": Permissions.from_dict(obj["cashOut"]) if obj.get("cashOut") is not None else None,
            "cashboxAdjustment": Permissions.from_dict(obj["cashboxAdjustment"]) if obj.get("cashboxAdjustment") is not None else None,
            "commissionReportIn": Permissions.from_dict(obj["commissionReportIn"]) if obj.get("commissionReportIn") is not None else None,
            "commissionReportOut": Permissions.from_dict(obj["commissionReportOut"]) if obj.get("commissionReportOut") is not None else None,
            "company": Permissions.from_dict(obj["company"]) if obj.get("company") is not None else None,
            "contract": Permissions.from_dict(obj["contract"]) if obj.get("contract") is not None else None,
            "counterpartyAdjustment": Permissions.from_dict(obj["counterpartyAdjustment"]) if obj.get("counterpartyAdjustment") is not None else None,
            "country": Permissions.from_dict(obj["country"]) if obj.get("country") is not None else None,
            "crptCancellation": Permissions.from_dict(obj["crptCancellation"]) if obj.get("crptCancellation") is not None else None,
            "crptPackageCreation": Permissions.from_dict(obj["crptPackageCreation"]) if obj.get("crptPackageCreation") is not None else None,
            "crptPackageDisaggregation": Permissions.from_dict(obj["crptPackageDisaggregation"]) if obj.get("crptPackageDisaggregation") is not None else None,
            "crptPackageItemRemoval": Permissions.from_dict(obj["crptPackageItemRemoval"]) if obj.get("crptPackageItemRemoval") is not None else None,
            "currency": Permissions.from_dict(obj["currency"]) if obj.get("currency") is not None else None,
            "customEntity": Permissions.from_dict(obj["customEntity"]) if obj.get("customEntity") is not None else None,
            "customerOrder": Permissions.from_dict(obj["customerOrder"]) if obj.get("customerOrder") is not None else None,
            "demand": Permissions.from_dict(obj["demand"]) if obj.get("demand") is not None else None,
            "emissionOrder": Permissions.from_dict(obj["emissionOrder"]) if obj.get("emissionOrder") is not None else None,
            "utilizationReport": Permissions.from_dict(obj["utilizationReport"]) if obj.get("utilizationReport") is not None else None,
            "atkAggregation": Permissions.from_dict(obj["atkAggregation"]) if obj.get("atkAggregation") is not None else None,
            "retireOrderOSU": Permissions.from_dict(obj["retireOrderOSU"]) if obj.get("retireOrderOSU") is not None else None,
            "employee": Permissions.from_dict(obj["employee"]) if obj.get("employee") is not None else None,
            "enrollOrder": Permissions.from_dict(obj["enrollOrder"]) if obj.get("enrollOrder") is not None else None,
            "enrollReturn": Permissions.from_dict(obj["enrollReturn"]) if obj.get("enrollReturn") is not None else None,
            "enter": Permissions.from_dict(obj["enter"]) if obj.get("enter") is not None else None,
            "expenseitem": Permissions.from_dict(obj["expenseitem"]) if obj.get("expenseitem") is not None else None,
            "factureIn": Permissions.from_dict(obj["factureIn"]) if obj.get("factureIn") is not None else None,
            "factureOut": Permissions.from_dict(obj["factureOut"]) if obj.get("factureOut") is not None else None,
            "good": Permissions.from_dict(obj["good"]) if obj.get("good") is not None else None,
            "internalOrder": Permissions.from_dict(obj["internalOrder"]) if obj.get("internalOrder") is not None else None,
            "inventory": Permissions.from_dict(obj["inventory"]) if obj.get("inventory") is not None else None,
            "invoiceIn": Permissions.from_dict(obj["invoiceIn"]) if obj.get("invoiceIn") is not None else None,
            "invoiceOut": Permissions.from_dict(obj["invoiceOut"]) if obj.get("invoiceOut") is not None else None,
            "loss": Permissions.from_dict(obj["loss"]) if obj.get("loss") is not None else None,
            "move": Permissions.from_dict(obj["move"]) if obj.get("move") is not None else None,
            "myCompany": Permissions.from_dict(obj["myCompany"]) if obj.get("myCompany") is not None else None,
            "paymentIn": Permissions.from_dict(obj["paymentIn"]) if obj.get("paymentIn") is not None else None,
            "paymentOut": Permissions.from_dict(obj["paymentOut"]) if obj.get("paymentOut") is not None else None,
            "prepayment": Permissions.from_dict(obj["prepayment"]) if obj.get("prepayment") is not None else None,
            "prepaymentReturn": Permissions.from_dict(obj["prepaymentReturn"]) if obj.get("prepaymentReturn") is not None else None,
            "priceList": Permissions.from_dict(obj["priceList"]) if obj.get("priceList") is not None else None,
            "processing": Permissions.from_dict(obj["processing"]) if obj.get("processing") is not None else None,
            "processingOrder": Permissions.from_dict(obj["processingOrder"]) if obj.get("processingOrder") is not None else None,
            "processingPlan": Permissions.from_dict(obj["processingPlan"]) if obj.get("processingPlan") is not None else None,
            "processingStage": Permissions.from_dict(obj["processingStage"]) if obj.get("processingStage") is not None else None,
            "processingProcess": Permissions.from_dict(obj["processingProcess"]) if obj.get("processingProcess") is not None else None,
            "productionTask": Permissions.from_dict(obj["productionTask"]) if obj.get("productionTask") is not None else None,
            "productionStageCompletion": Permissions.from_dict(obj["productionStageCompletion"]) if obj.get("productionStageCompletion") is not None else None,
            "project": Permissions.from_dict(obj["project"]) if obj.get("project") is not None else None,
            "purchaseOrder": Permissions.from_dict(obj["purchaseOrder"]) if obj.get("purchaseOrder") is not None else None,
            "purchaseReturn": Permissions.from_dict(obj["purchaseReturn"]) if obj.get("purchaseReturn") is not None else None,
            "remainsOrder": Permissions.from_dict(obj["remainsOrder"]) if obj.get("remainsOrder") is not None else None,
            "remarkingOrder": Permissions.from_dict(obj["remarkingOrder"]) if obj.get("remarkingOrder") is not None else None,
            "retailDemand": Permissions.from_dict(obj["retailDemand"]) if obj.get("retailDemand") is not None else None,
            "retailDrawerCashIn": Permissions.from_dict(obj["retailDrawerCashIn"]) if obj.get("retailDrawerCashIn") is not None else None,
            "retailDrawerCashOut": Permissions.from_dict(obj["retailDrawerCashOut"]) if obj.get("retailDrawerCashOut") is not None else None,
            "retailSalesReturn": Permissions.from_dict(obj["retailSalesReturn"]) if obj.get("retailSalesReturn") is not None else None,
            "retailShift": Permissions.from_dict(obj["retailShift"]) if obj.get("retailShift") is not None else None,
            "retailStore": Permissions.from_dict(obj["retailStore"]) if obj.get("retailStore") is not None else None,
            "retireOrder": Permissions.from_dict(obj["retireOrder"]) if obj.get("retireOrder") is not None else None,
            "salesReturn": Permissions.from_dict(obj["salesReturn"]) if obj.get("salesReturn") is not None else None,
            "salesChannel": Permissions.from_dict(obj["salesChannel"]) if obj.get("salesChannel") is not None else None,
            "script": ScriptPermissions.from_dict(obj["script"]) if obj.get("script") is not None else None,
            "scriptTemplate": ScriptTemplatePermissions.from_dict(obj["scriptTemplate"]) if obj.get("scriptTemplate") is not None else None,
            "supply": Permissions.from_dict(obj["supply"]) if obj.get("supply") is not None else None,
            "taxrate": Permissions.from_dict(obj["taxrate"]) if obj.get("taxrate") is not None else None,
            "trackingCodeList": Permissions.from_dict(obj["trackingCodeList"]) if obj.get("trackingCodeList") is not None else None,
            "uom": Permissions.from_dict(obj["uom"]) if obj.get("uom") is not None else None,
            "warehouse": Permissions.from_dict(obj["warehouse"]) if obj.get("warehouse") is not None else None
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj

































































from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.script_permissions import ScriptPermissions



from moysklad_remap_12_sdk.models.script_template_permissions import ScriptTemplatePermissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



from moysklad_remap_12_sdk.models.permissions import Permissions



