# coding: utf-8

"""
    МойСклад JSON API

    API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from moysklad_remap_12_sdk.models.meta import Meta
from moysklad_remap_12_sdk.models.product_folder import ProductFolder
from moysklad_remap_12_sdk.models.special_price_discount_special_price import SpecialPriceDiscountSpecialPrice
from typing import Optional, Set
from typing_extensions import Self

from moysklad_remap_12_sdk.models.discount_abstract import DiscountAbstract

class SpecialPriceDiscount(DiscountAbstract):
    """
    Специальная цена (specialpricediscount)
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="ID дополнительного поля")
    meta: Optional[Meta] = None
    product_folders: Optional[List[ProductFolder]] = Field(default=None, description="Группы товаров со скидкой", alias="productFolders")
    use_price_type: Optional[StrictBool] = Field(default=None, description="Использовать ли специальную цену", alias="usePriceType")
    discount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Процент скидки (используется при usePriceType=false)")
    special_price: Optional[SpecialPriceDiscountSpecialPrice] = Field(default=None, alias="specialPrice")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "meta", "productFolders", "usePriceType", "discount", "specialPrice"]

    model_config = ConfigDict(
        extra="allow",
        arbitrary_types_allowed=True,
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @classmethod
    def create_with_meta(
        cls,
        id: str,
    ) -> Self:
        """Create a reference with ``meta`` populated for this entity."""
        from moysklad_remap_12_sdk.configuration import Configuration
        from moysklad_remap_12_sdk.models.meta import Meta

        href = Configuration.get_default().host + "/entity" + "/specialpricediscount" + "/" + id
        return cls(
            id=id,
            meta=Meta(
                href=href,
                type="specialpricediscount",
                media_type="application/json",
            ),
        )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpecialPriceDiscount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        `None` is only added for nullable fields set at initialization.
        OpenAPI `readOnly` response fields are retained.
        """
        excluded_fields: Set[str] = {
            "additional_properties",
        }

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        _items = []
        if self.product_folders:
            for _item_product_folders in self.product_folders:
                if _item_product_folders:
                    _items.append(_item_product_folders.to_dict())
            _dict['productFolders'] = _items
        if self.special_price:
            _dict['specialPrice'] = self.special_price.to_dict()
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.discount is None and "discount" in self.model_fields_set:
            _dict['discount'] = None

        if self.special_price is None and "special_price" in self.model_fields_set:
            _dict['specialPrice'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpecialPriceDiscount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = dict(obj)
        _data.update({
            "id": obj.get("id"),
            "meta": Meta.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "productFolders": [ProductFolder.from_dict(_item) for _item in obj["productFolders"]] if obj.get("productFolders") is not None else None,
            "usePriceType": obj.get("usePriceType"),
            "discount": obj.get("discount"),
            "specialPrice": SpecialPriceDiscountSpecialPrice.from_dict(obj["specialPrice"]) if obj.get("specialPrice") is not None else None
        })
        _obj = cls.model_validate(_data)
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj





from moysklad_remap_12_sdk.models.meta import Meta




from moysklad_remap_12_sdk.models.product_folder import ProductFolder






from moysklad_remap_12_sdk.models.special_price_discount_special_price import SpecialPriceDiscountSpecialPrice



